// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 08:50 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model9_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__10 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__10</summary>
		public bool Changed_numberOfIterations_vString__10_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__10 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__10</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__10_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__10 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__10</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__10_isInitialised;
		/// <summary>True if Changed_vString__10 has executed. Set this to false to force re-execution of Changed_vString__10</summary>
		public bool Changed_vString__10_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__20'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__20_marginal_F;
		/// <summary>The constant 'vDirichlet10'</summary>
		public Dirichlet vDirichlet10;
		/// <summary>Message to marginal of 'vint__20'</summary>
		public DistributionRefArray<Discrete,int> vint__20_marginal_F;
		/// <summary>Field backing the vString__10 property</summary>
		private string[] vString__10_field;
		/// <summary>Message to marginal of 'vString__10'</summary>
		public DistributionRefArray<StringDistribution,string> vString__10_marginal_F;
		public StringDistribution[] vString82_F;
		public StringDistribution[] vString84_B;
		/// <summary>Message to marginal of 'vVector__20'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__20_marginal_F;
		public Dirichlet[][] vVector__20_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__20_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__10'</summary>
		public string[] vString__10
		{
			get {
				return this.vString__10_field;
			}
			set {
				if ((value!=null)&&(value.Length!=30)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+30)+" was expected for variable \'vString__10\'");
				}
				this.vString__10_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__10_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__10_isInitialised = false;
				this.Changed_numberOfIterations_vString__10_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__10</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__10(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__10_isDone) {
				return ;
			}
			// Create array for 'vVector__20_marginal' Forwards messages.
			this.vVector__20_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__20_rep_F_marginal'
			Dirichlet[] vVector__20_rep_F_marginal = new Dirichlet[8];
			for(int index20 = 0; index20<8; index20++) {
				vVector__20_rep_F_marginal[index20] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet10);
			}
			// Create array for replicates of 'vVector__20_rep_F'
			Dirichlet[][] vVector__20_rep_F = new Dirichlet[8][];
			for(int index20 = 0; index20<8; index20++) {
				// Create array for 'vVector__20_rep' Forwards messages.
				vVector__20_rep_F[index20] = new Dirichlet[30];
			}
			for(int index21 = 0; index21<30; index21++) {
				for(int index20 = 0; index20<8; index20++) {
					vVector__20_rep_F[index20][index21] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet10.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__20_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__20_F = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vChar__20' Forwards messages.
				vChar__20_F[index21] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index20 = 0; index20<8; index20++) {
					vChar__20_F[index21][index20] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString81_F'
			StringDistribution[] vString81_F = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString81_F[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString84_F'
			StringDistribution[] vString84_F = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString84_F[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString83_use_B'
			StringDistribution[] vString83_use_B = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString83_use_B[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint119_B'
			Discrete[] vint119_B = new Discrete[30];
			for(int index21 = 0; index21<30; index21++) {
				vint119_B[index21] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
			}
			DiscreteChar vDiscreteChar30 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__20_index21__0__uses_B'
			Discrete[][] vint__20_index21__0__uses_B = new Discrete[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vint__20_index21__0__uses' Backwards messages.
				vint__20_index21__0__uses_B[index21] = new Discrete[2];
				vint__20_index21__0__uses_B[index21][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				vint__20_index21__0__uses_B[index21][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
			}
			// Create array for replicates of 'vint__20_index21__0__uses_F'
			Discrete[][] vint__20_index21__0__uses_F = new Discrete[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vint__20_index21__0__uses' Forwards messages.
				vint__20_index21__0__uses_F[index21] = new Discrete[2];
				vint__20_index21__0__uses_F[index21][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				vint__20_index21__0__uses_F[index21][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
			}
			Discrete vint__20_F_reduced;
			vint__20_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
			// Create array for replicates of 'vString82_use_B'
			StringDistribution[] vString82_use_B = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString82_use_B[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint119_F'
			Discrete[] vint119_F = new Discrete[30];
			for(int index21 = 0; index21<30; index21++) {
				vint119_F[index21] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
			}
			// Create array for replicates of 'vString83_F'
			StringDistribution[] vString83_F = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString83_F[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString81_B'
			StringDistribution[] vString81_B = new StringDistribution[30];
			for(int index21 = 0; index21<30; index21++) {
				vString81_B[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__20_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__20_use_B = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vChar__20_use' Backwards messages.
				vChar__20_use_B[index21] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index20 = 0; index20<8; index20++) {
					vChar__20_use_B[index21][index20] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__20__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__20__0__B = new DistributionRefArray<Dirichlet,Vector>[30];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vVector__20__0_' Backwards messages.
				vVector__20__0__B[index21] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index20 = 0; index20<8; index20++) {
					vVector__20__0__B[index21][index20] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet10.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__20__B'
			Dirichlet[][][] vVector__20__B = new Dirichlet[30][][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vVector__20_' Backwards messages.
				vVector__20__B[index21] = new Dirichlet[8][];
				for(int index20 = 0; index20<8; index20++) {
					// Create array for 'vVector__20_' Backwards messages.
					vVector__20__B[index21][index20] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__20__B[index21][index20][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet10.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__20_index21__selector_cases_0_uses_B'
			Bernoulli[][] vbool__20_index21__selector_cases_0_uses_B = new Bernoulli[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vbool__20_index21__selector_cases_0_uses' Backwards messages.
				vbool__20_index21__selector_cases_0_uses_B[index21] = new Bernoulli[27];
				vbool__20_index21__selector_cases_0_uses_B[index21][25] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][24] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][23] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][22] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][21] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][20] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][19] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][18] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][17] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][16] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][15] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][14] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][11] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][10] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][9] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][8] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][7] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][6] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][5] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][4] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][3] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][2] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][1] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][0] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][12] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][13] = Bernoulli.Uniform();
				vbool__20_index21__selector_cases_0_uses_B[index21][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__20_index21__selector_cases_0_B'
			Bernoulli[] vbool__20_index21__selector_cases_0_B = new Bernoulli[30];
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_cases_0_B[index21] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__20_index21__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__20_index21__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[30];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vbool__20_index21__selector_cases' Backwards messages.
				vbool__20_index21__selector_cases_B[index21] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__20_index21__selector_cases_B[index21][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__20_index21__selector_uses_B'
			Bernoulli[][] vbool__20_index21__selector_uses_B = new Bernoulli[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vbool__20_index21__selector_uses' Backwards messages.
				vbool__20_index21__selector_uses_B[index21] = new Bernoulli[3];
				vbool__20_index21__selector_uses_B[index21][2] = Bernoulli.Uniform();
				vbool__20_index21__selector_uses_B[index21][1] = Bernoulli.Uniform();
				vbool__20_index21__selector_uses_B[index21][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__20_index21__selector_cases_1_B'
			Bernoulli[] vbool__20_index21__selector_cases_1_B = new Bernoulli[30];
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_cases_1_B[index21] = Bernoulli.Uniform();
				// Message to 'vbool__20_index21__selector_cases_1' from StringOfLength factor
				vbool__20_index21__selector_cases_1_B[index21] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar30, 100, this.vString__10[index21]));
				// Message to 'vbool__20_index21__selector_cases' from Copy factor
				vbool__20_index21__selector_cases_B[index21][1] = ArrayHelper.SetTo<Bernoulli>(vbool__20_index21__selector_cases_B[index21][1], vbool__20_index21__selector_cases_1_B[index21]);
			}
			// Create array for replicates of 'vbool__20_index21__selector_uses_B_toDef'
			Bernoulli[] vbool__20_index21__selector_uses_B_toDef = new Bernoulli[30];
			Bernoulli vBernoulli10 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_uses_B_toDef[index21] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli10);
			}
			// Create array for replicates of 'vbool__20_index21__selector_uses_F_marginal'
			Bernoulli[] vbool__20_index21__selector_uses_F_marginal = new Bernoulli[30];
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_uses_F_marginal[index21] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli10);
			}
			// Create array for replicates of 'vbool__20_index21__selector_uses_F'
			Bernoulli[][] vbool__20_index21__selector_uses_F = new Bernoulli[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vbool__20_index21__selector_uses' Forwards messages.
				vbool__20_index21__selector_uses_F[index21] = new Bernoulli[3];
				vbool__20_index21__selector_uses_F[index21][1] = Bernoulli.Uniform();
				vbool__20_index21__selector_uses_F[index21][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__20_index21__selector_rep_B_toDef'
			Bernoulli[] vbool__20_index21__selector_rep_B_toDef = new Bernoulli[30];
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_rep_B_toDef[index21] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__20_index21__selector_uses_F[index21][1]);
			}
			// Create array for replicates of 'vbool__20_index21__selector_rep_F_marginal'
			Bernoulli[] vbool__20_index21__selector_rep_F_marginal = new Bernoulli[30];
			for(int index21 = 0; index21<30; index21++) {
				vbool__20_index21__selector_rep_F_marginal[index21] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__20_index21__selector_uses_F[index21][1]);
			}
			// Create array for replicates of 'vbool__20_index21__selector_rep_F'
			Bernoulli[][] vbool__20_index21__selector_rep_F = new Bernoulli[30][];
			for(int index21 = 0; index21<30; index21++) {
				// Create array for 'vbool__20_index21__selector_rep' Forwards messages.
				vbool__20_index21__selector_rep_F[index21] = new Bernoulli[8];
				for(int index20 = 0; index20<8; index20++) {
					vbool__20_index21__selector_rep_F[index21][index20] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__20_index21__selector_rep_B_reduced = default(Bernoulli);
			vbool__20_index21__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index20 = 0; index20<8; index20++) {
					vVector__20_rep_F_marginal[index20] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__20_rep_B_toDef[index20], this.vDirichlet10, vVector__20_rep_F_marginal[index20]);
				}
				for(int index21 = 0; index21<30; index21++) {
					for(int index20 = 0; index20<8; index20++) {
						// Message to 'vVector__20_rep' from Replicate factor
						vVector__20_rep_F[index20][index21] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__20_rep_B[index20][index21], vVector__20_rep_F_marginal[index20], index21, vVector__20_rep_F[index20][index21]);
						// Message to 'vChar__20' from Char factor
						vChar__20_F[index21][index20] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__20_rep_F[index20][index21]);
					}
					// Message to 'vString81' from StringFromArray factor
					vString81_F[index21] = StringFromArrayOp.StrAverageConditional(vChar__20_F[index21]);
					// Message to 'vString84' from Concat factor
					vString84_F[index21] = StringConcatOp.ConcatAverageConditional(this.vString82_F[index21], vString81_F[index21]);
					// Message to 'vString83_use' from Concat factor
					vString83_use_B[index21] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__10[index21]), vString84_F[index21]);
					// Message to 'vint119' from StringOfLength factor
					vint119_B[index21] = StringOfLengthOp.LengthAverageConditional(vString83_use_B[index21], vDiscreteChar30, vint119_B[index21]);
					// Message to 'vint__20_index21__0__uses' from Difference factor
					vint__20_index21__0__uses_B[index21][0] = IntegerPlusOp.BAverageConditional(92, vint119_B[index21], vint__20_index21__0__uses_B[index21][0]);
					// Message to 'vint__20_index21__0__uses' from Replicate factor
					vint__20_index21__0__uses_F[index21][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__20_index21__0__uses_B[index21], vint__20_F_reduced, 1, vint__20_index21__0__uses_F[index21][1]);
					// Message to 'vString82' from StringOfLength factor
					this.vString82_F[index21] = StringOfLengthOp.StrAverageConditional(vDiscreteChar30, vint__20_index21__0__uses_F[index21][1]);
					// Message to 'vString82_use' from Concat factor
					vString82_use_B[index21] = StringConcatOp.Str1AverageConditional(this.vString84_B[index21], vString81_F[index21]);
					// Message to 'vint__20_index21__0__uses' from StringOfLength factor
					vint__20_index21__0__uses_B[index21][1] = StringOfLengthOp.LengthAverageConditional(vString82_use_B[index21], vDiscreteChar30, vint__20_index21__0__uses_B[index21][1]);
					// Message to 'vint__20_index21__0__uses' from Replicate factor
					vint__20_index21__0__uses_F[index21][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__20_index21__0__uses_B[index21], vint__20_F_reduced, 0, vint__20_index21__0__uses_F[index21][0]);
					// Message to 'vint119' from Difference factor
					vint119_F[index21] = IntegerPlusOp.AAverageConditional(92, vint__20_index21__0__uses_F[index21][0], vint119_F[index21]);
					// Message to 'vString83' from StringOfLength factor
					vString83_F[index21] = StringOfLengthOp.StrAverageConditional(vDiscreteChar30, vint119_F[index21]);
					// Message to 'vString84' from Concat factor
					this.vString84_B[index21] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__10[index21]), vString83_F[index21]);
					// Message to 'vString81' from Concat factor
					vString81_B[index21] = StringConcatOp.Str2AverageConditional(this.vString84_B[index21], this.vString82_F[index21]);
					// Message to 'vChar__20_use' from StringFromArray factor
					vChar__20_use_B[index21] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString81_B[index21], vChar__20_F[index21], vChar__20_use_B[index21]);
					// Message to 'vbool__20_index21__selector_cases_0_uses' from Concat factor
					vbool__20_index21__selector_cases_0_uses_B[index21][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__10[index21], vString84_F[index21], vString83_F[index21]));
					// Message to 'vbool__20_index21__selector_cases_0_uses' from Difference factor
					vbool__20_index21__selector_cases_0_uses_B[index21][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(92, vint119_B[index21], vint__20_index21__0__uses_F[index21][0]));
					// Message to 'vbool__20_index21__selector_cases_0_uses' from Replicate factor
					vbool__20_index21__selector_cases_0_uses_B[index21][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__20_index21__0__uses_B[index21], vint__20_F_reduced, vint__20_index21__0__uses_F[index21]));
					// Message to 'vbool__20_index21__selector_cases_0' from Replicate factor
					vbool__20_index21__selector_cases_0_B[index21] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__20_index21__selector_cases_0_uses_B[index21], vbool__20_index21__selector_cases_0_B[index21]);
					// Message to 'vbool__20_index21__selector_cases' from Copy factor
					vbool__20_index21__selector_cases_B[index21][0] = ArrayHelper.SetTo<Bernoulli>(vbool__20_index21__selector_cases_B[index21][0], vbool__20_index21__selector_cases_0_B[index21]);
					// Message to 'vbool__20_index21__selector_uses' from Cases factor
					vbool__20_index21__selector_uses_B[index21][0] = CasesOp.BAverageConditional(vbool__20_index21__selector_cases_B[index21]);
					vbool__20_index21__selector_uses_B_toDef[index21] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__20_index21__selector_uses_B[index21], vbool__20_index21__selector_uses_B_toDef[index21]);
					vbool__20_index21__selector_uses_F_marginal[index21] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__20_index21__selector_uses_B_toDef[index21], vBernoulli10, vbool__20_index21__selector_uses_F_marginal[index21]);
					// Message to 'vbool__20_index21__selector_uses' from Replicate factor
					vbool__20_index21__selector_uses_F[index21][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__20_index21__selector_rep_B_toDef[index21], vbool__20_index21__selector_uses_F_marginal[index21], 1, vbool__20_index21__selector_uses_F[index21][1]);
					vbool__20_index21__selector_rep_F_marginal[index21] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__20_index21__selector_rep_B_toDef[index21], vbool__20_index21__selector_uses_F[index21][1], vbool__20_index21__selector_rep_F_marginal[index21]);
					for(int index20 = 0; index20<8; index20++) {
						// Message to 'vVector__20__0_' from Char factor
						vVector__20__0__B[index21][index20] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__20_use_B[index21][index20], vVector__20_rep_F[index20][index21], vVector__20__0__B[index21][index20]);
						// Message to 'vVector__20_' from Copy factor
						vVector__20__B[index21][index20][0] = ArrayHelper.SetTo<Dirichlet>(vVector__20__B[index21][index20][0], vVector__20__0__B[index21][index20]);
						// Message to 'vbool__20_index21__selector_rep' from Replicate factor
						vbool__20_index21__selector_rep_F[index21][index20] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__20_index21__selector_rep_B_reduced, vbool__20_index21__selector_rep_F_marginal[index21], index20, vbool__20_index21__selector_rep_F[index21][index20]);
						// Message to 'vVector__20_rep' from EnterPartial factor
						this.vVector__20_rep_B[index20][index21] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__20__B[index21][index20], vbool__20_index21__selector_rep_F[index21][index20], vVector__20_rep_F[index20][index21], new int[1] { 0 }, this.vVector__20_rep_B[index20][index21]);
					}
				}
				for(int index20 = 0; index20<8; index20++) {
					this.vVector__20_rep_B_toDef[index20] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__20_rep_B[index20], this.vVector__20_rep_B_toDef[index20]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index20 = 0; index20<8; index20++) {
				this.vVector__20_marginal_F[index20] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet10.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__20_marginal' from Variable factor
				this.vVector__20_marginal_F[index20] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__20_rep_B_toDef[index20], this.vDirichlet10, this.vVector__20_marginal_F[index20]);
			}
			// Create array for 'vint__20_marginal' Forwards messages.
			this.vint__20_marginal_F = new DistributionRefArray<Discrete,int>(30);
			// Create array for replicates of 'vint__20_index21__0__B'
			Discrete[] vint__20_index21__0__B = new Discrete[30];
			// Create array for replicates of 'vint__20_index21__B'
			Discrete[][] vint__20_index21__B = new Discrete[30][];
			DistributionRefArray<Discrete,int> vint__20_use_B;
			// Create array for 'vint__20_use' Backwards messages.
			vint__20_use_B = new DistributionRefArray<Discrete,int>(30);
			for(int index21 = 0; index21<30; index21++) {
				this.vint__20_marginal_F[index21] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				vint__20_use_B[index21] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				// Message to 'vbool__20_index21__selector_uses' from Replicate factor
				vbool__20_index21__selector_uses_F[index21][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__20_index21__selector_uses_B[index21][2], vbool__20_index21__selector_uses_F_marginal[index21], 2, vbool__20_index21__selector_uses_F[index21][2]);
				// Create array for 'vint__20_index21_' Backwards messages.
				vint__20_index21__B[index21] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__20_index21__B[index21][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				}
				vint__20_index21__0__B[index21] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(93));
				// Message to 'vint__20_index21__0_' from Replicate factor
				vint__20_index21__0__B[index21] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__20_index21__0__uses_B[index21], vint__20_index21__0__B[index21]);
				// Message to 'vint__20_index21_' from Copy factor
				vint__20_index21__B[index21][0] = ArrayHelper.SetTo<Discrete>(vint__20_index21__B[index21][0], vint__20_index21__0__B[index21]);
				// Message to 'vint__20_use' from EnterPartial factor
				vint__20_use_B[index21] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__20_index21__B[index21], vbool__20_index21__selector_uses_F[index21][2], vint__20_F_reduced, new int[1] { 0 }, vint__20_use_B[index21]);
				// Message to 'vint__20_marginal' from Variable factor
				this.vint__20_marginal_F[index21] = VariableOp.MarginalAverageConditional<Discrete>(vint__20_use_B[index21], vint__20_F_reduced, this.vint__20_marginal_F[index21]);
			}
			// Create array for 'vbool__20_marginal' Forwards messages.
			this.vbool__20_marginal_F = new DistributionStructArray<Bernoulli,bool>(30);
			for(int index21 = 0; index21<30; index21++) {
				this.vbool__20_marginal_F[index21] = Bernoulli.Uniform();
				// Message to 'vbool__20_marginal' from Variable factor
				this.vbool__20_marginal_F[index21] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__20_index21__selector_uses_B_toDef[index21], vBernoulli10, this.vbool__20_marginal_F[index21]);
			}
			this.Changed_numberOfIterations_vString__10_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__10</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__10(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__10_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__10_isInitialised)) {
				return ;
			}
			for(int index20 = 0; index20<8; index20++) {
				this.vVector__20_rep_B_toDef[index20] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet10);
			}
			for(int index21 = 0; index21<30; index21++) {
				for(int index20 = 0; index20<8; index20++) {
					this.vVector__20_rep_B[index20][index21] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet10.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString82_F[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString84_B[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__10_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__10_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__10</summary>
		private void Changed_vString__10()
		{
			if (this.Changed_vString__10_isDone) {
				return ;
			}
			// Create array for 'vString__10_marginal' Forwards messages.
			this.vString__10_marginal_F = new DistributionRefArray<StringDistribution,string>(30);
			for(int index21 = 0; index21<30; index21++) {
				this.vString__10_marginal_F[index21] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__10_marginal' from DerivedVariable factor
			this.vString__10_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__10, this.vString__10_marginal_F);
			this.Changed_vString__10_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet10 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__20_rep_B_toDef'
			this.vVector__20_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__20_rep_B'
			this.vVector__20_rep_B = new Dirichlet[8][];
			for(int index20 = 0; index20<8; index20++) {
				// Create array for 'vVector__20_rep' Backwards messages.
				this.vVector__20_rep_B[index20] = new Dirichlet[30];
			}
			// Create array for replicates of 'vString82_F'
			this.vString82_F = new StringDistribution[30];
			// Create array for replicates of 'vString84_B'
			this.vString84_B = new StringDistribution[30];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__10_isDone = false;
				}
				this.Changed_numberOfIterations_vString__10_isDone = false;
			}
			this.Changed_vString__10();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__10(initialise);
			this.Changed_numberOfIterations_vString__10(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__10") {
				return this.vString__10;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__10") {
				return this.VString__10Marginal();
			}
			if (variableName=="vVector__20") {
				return this.VVector__20Marginal();
			}
			if (variableName=="vint__20") {
				return this.Vint__20Marginal();
			}
			if (variableName=="vbool__20") {
				return this.Vbool__20Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__10") {
				this.vString__10 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__20' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__20Marginal()
		{
			return this.vbool__20_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__20' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__20Marginal()
		{
			return this.vint__20_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__10' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__10Marginal()
		{
			return this.vString__10_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__20' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__20Marginal()
		{
			return this.vVector__20_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
