// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 08:49 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model4_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__5 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__5</summary>
		public bool Changed_numberOfIterations_vString__5_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__5 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__5</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__5_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__5 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__5</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__5_isInitialised;
		/// <summary>True if Changed_vString__5 has executed. Set this to false to force re-execution of Changed_vString__5</summary>
		public bool Changed_vString__5_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__10'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__10_marginal_F;
		/// <summary>The constant 'vDirichlet5'</summary>
		public Dirichlet vDirichlet5;
		/// <summary>Message to marginal of 'vint__10'</summary>
		public DistributionRefArray<Discrete,int> vint__10_marginal_F;
		/// <summary>Field backing the vString__5 property</summary>
		private string[] vString__5_field;
		/// <summary>Message to marginal of 'vString__5'</summary>
		public DistributionRefArray<StringDistribution,string> vString__5_marginal_F;
		public StringDistribution[] vString42_F;
		public StringDistribution[] vString44_B;
		/// <summary>Message to marginal of 'vVector__10'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__10_marginal_F;
		public Dirichlet[][] vVector__10_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__10_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__5'</summary>
		public string[] vString__5
		{
			get {
				return this.vString__5_field;
			}
			set {
				if ((value!=null)&&(value.Length!=30)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+30)+" was expected for variable \'vString__5\'");
				}
				this.vString__5_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__5_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__5_isInitialised = false;
				this.Changed_numberOfIterations_vString__5_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__5</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__5(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__5_isDone) {
				return ;
			}
			// Create array for 'vVector__10_marginal' Forwards messages.
			this.vVector__10_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__10_rep_F_marginal'
			Dirichlet[] vVector__10_rep_F_marginal = new Dirichlet[8];
			for(int index10 = 0; index10<8; index10++) {
				vVector__10_rep_F_marginal[index10] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet5);
			}
			// Create array for replicates of 'vVector__10_rep_F'
			Dirichlet[][] vVector__10_rep_F = new Dirichlet[8][];
			for(int index10 = 0; index10<8; index10++) {
				// Create array for 'vVector__10_rep' Forwards messages.
				vVector__10_rep_F[index10] = new Dirichlet[30];
			}
			for(int index11 = 0; index11<30; index11++) {
				for(int index10 = 0; index10<8; index10++) {
					vVector__10_rep_F[index10][index11] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet5.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__10_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__10_F = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vChar__10' Forwards messages.
				vChar__10_F[index11] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index10 = 0; index10<8; index10++) {
					vChar__10_F[index11][index10] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString41_F'
			StringDistribution[] vString41_F = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString41_F[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString44_F'
			StringDistribution[] vString44_F = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString44_F[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString43_use_B'
			StringDistribution[] vString43_use_B = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString43_use_B[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint64_B'
			Discrete[] vint64_B = new Discrete[30];
			for(int index11 = 0; index11<30; index11++) {
				vint64_B[index11] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			DiscreteChar vDiscreteChar15 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__10_index11__0__uses_B'
			Discrete[][] vint__10_index11__0__uses_B = new Discrete[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vint__10_index11__0__uses' Backwards messages.
				vint__10_index11__0__uses_B[index11] = new Discrete[2];
				vint__10_index11__0__uses_B[index11][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__10_index11__0__uses_B[index11][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			// Create array for replicates of 'vint__10_index11__0__uses_F'
			Discrete[][] vint__10_index11__0__uses_F = new Discrete[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vint__10_index11__0__uses' Forwards messages.
				vint__10_index11__0__uses_F[index11] = new Discrete[2];
				vint__10_index11__0__uses_F[index11][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__10_index11__0__uses_F[index11][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			Discrete vint__10_F_reduced;
			vint__10_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			// Create array for replicates of 'vString42_use_B'
			StringDistribution[] vString42_use_B = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString42_use_B[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint64_F'
			Discrete[] vint64_F = new Discrete[30];
			for(int index11 = 0; index11<30; index11++) {
				vint64_F[index11] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			// Create array for replicates of 'vString43_F'
			StringDistribution[] vString43_F = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString43_F[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString41_B'
			StringDistribution[] vString41_B = new StringDistribution[30];
			for(int index11 = 0; index11<30; index11++) {
				vString41_B[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__10_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__10_use_B = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vChar__10_use' Backwards messages.
				vChar__10_use_B[index11] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index10 = 0; index10<8; index10++) {
					vChar__10_use_B[index11][index10] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__10__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__10__0__B = new DistributionRefArray<Dirichlet,Vector>[30];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vVector__10__0_' Backwards messages.
				vVector__10__0__B[index11] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index10 = 0; index10<8; index10++) {
					vVector__10__0__B[index11][index10] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet5.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__10__B'
			Dirichlet[][][] vVector__10__B = new Dirichlet[30][][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vVector__10_' Backwards messages.
				vVector__10__B[index11] = new Dirichlet[8][];
				for(int index10 = 0; index10<8; index10++) {
					// Create array for 'vVector__10_' Backwards messages.
					vVector__10__B[index11][index10] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__10__B[index11][index10][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet5.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__10_index11__selector_cases_0_uses_B'
			Bernoulli[][] vbool__10_index11__selector_cases_0_uses_B = new Bernoulli[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vbool__10_index11__selector_cases_0_uses' Backwards messages.
				vbool__10_index11__selector_cases_0_uses_B[index11] = new Bernoulli[27];
				vbool__10_index11__selector_cases_0_uses_B[index11][25] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][24] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][23] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][22] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][21] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][20] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][19] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][18] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][17] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][16] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][15] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][14] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][11] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][10] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][9] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][8] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][7] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][6] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][5] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][4] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][3] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][2] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][1] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][0] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][12] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][13] = Bernoulli.Uniform();
				vbool__10_index11__selector_cases_0_uses_B[index11][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__10_index11__selector_cases_0_B'
			Bernoulli[] vbool__10_index11__selector_cases_0_B = new Bernoulli[30];
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_cases_0_B[index11] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__10_index11__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__10_index11__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[30];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vbool__10_index11__selector_cases' Backwards messages.
				vbool__10_index11__selector_cases_B[index11] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__10_index11__selector_cases_B[index11][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__10_index11__selector_uses_B'
			Bernoulli[][] vbool__10_index11__selector_uses_B = new Bernoulli[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vbool__10_index11__selector_uses' Backwards messages.
				vbool__10_index11__selector_uses_B[index11] = new Bernoulli[3];
				vbool__10_index11__selector_uses_B[index11][2] = Bernoulli.Uniform();
				vbool__10_index11__selector_uses_B[index11][1] = Bernoulli.Uniform();
				vbool__10_index11__selector_uses_B[index11][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__10_index11__selector_cases_1_B'
			Bernoulli[] vbool__10_index11__selector_cases_1_B = new Bernoulli[30];
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_cases_1_B[index11] = Bernoulli.Uniform();
				// Message to 'vbool__10_index11__selector_cases_1' from StringOfLength factor
				vbool__10_index11__selector_cases_1_B[index11] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar15, 50, this.vString__5[index11]));
				// Message to 'vbool__10_index11__selector_cases' from Copy factor
				vbool__10_index11__selector_cases_B[index11][1] = ArrayHelper.SetTo<Bernoulli>(vbool__10_index11__selector_cases_B[index11][1], vbool__10_index11__selector_cases_1_B[index11]);
			}
			// Create array for replicates of 'vbool__10_index11__selector_uses_B_toDef'
			Bernoulli[] vbool__10_index11__selector_uses_B_toDef = new Bernoulli[30];
			Bernoulli vBernoulli5 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_uses_B_toDef[index11] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli5);
			}
			// Create array for replicates of 'vbool__10_index11__selector_uses_F_marginal'
			Bernoulli[] vbool__10_index11__selector_uses_F_marginal = new Bernoulli[30];
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_uses_F_marginal[index11] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli5);
			}
			// Create array for replicates of 'vbool__10_index11__selector_uses_F'
			Bernoulli[][] vbool__10_index11__selector_uses_F = new Bernoulli[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vbool__10_index11__selector_uses' Forwards messages.
				vbool__10_index11__selector_uses_F[index11] = new Bernoulli[3];
				vbool__10_index11__selector_uses_F[index11][1] = Bernoulli.Uniform();
				vbool__10_index11__selector_uses_F[index11][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__10_index11__selector_rep_B_toDef'
			Bernoulli[] vbool__10_index11__selector_rep_B_toDef = new Bernoulli[30];
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_rep_B_toDef[index11] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__10_index11__selector_uses_F[index11][1]);
			}
			// Create array for replicates of 'vbool__10_index11__selector_rep_F_marginal'
			Bernoulli[] vbool__10_index11__selector_rep_F_marginal = new Bernoulli[30];
			for(int index11 = 0; index11<30; index11++) {
				vbool__10_index11__selector_rep_F_marginal[index11] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__10_index11__selector_uses_F[index11][1]);
			}
			// Create array for replicates of 'vbool__10_index11__selector_rep_F'
			Bernoulli[][] vbool__10_index11__selector_rep_F = new Bernoulli[30][];
			for(int index11 = 0; index11<30; index11++) {
				// Create array for 'vbool__10_index11__selector_rep' Forwards messages.
				vbool__10_index11__selector_rep_F[index11] = new Bernoulli[8];
				for(int index10 = 0; index10<8; index10++) {
					vbool__10_index11__selector_rep_F[index11][index10] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__10_index11__selector_rep_B_reduced = default(Bernoulli);
			vbool__10_index11__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index10 = 0; index10<8; index10++) {
					vVector__10_rep_F_marginal[index10] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__10_rep_B_toDef[index10], this.vDirichlet5, vVector__10_rep_F_marginal[index10]);
				}
				for(int index11 = 0; index11<30; index11++) {
					for(int index10 = 0; index10<8; index10++) {
						// Message to 'vVector__10_rep' from Replicate factor
						vVector__10_rep_F[index10][index11] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__10_rep_B[index10][index11], vVector__10_rep_F_marginal[index10], index11, vVector__10_rep_F[index10][index11]);
						// Message to 'vChar__10' from Char factor
						vChar__10_F[index11][index10] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__10_rep_F[index10][index11]);
					}
					// Message to 'vString41' from StringFromArray factor
					vString41_F[index11] = StringFromArrayOp.StrAverageConditional(vChar__10_F[index11]);
					// Message to 'vString44' from Concat factor
					vString44_F[index11] = StringConcatOp.ConcatAverageConditional(this.vString42_F[index11], vString41_F[index11]);
					// Message to 'vString43_use' from Concat factor
					vString43_use_B[index11] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__5[index11]), vString44_F[index11]);
					// Message to 'vint64' from StringOfLength factor
					vint64_B[index11] = StringOfLengthOp.LengthAverageConditional(vString43_use_B[index11], vDiscreteChar15, vint64_B[index11]);
					// Message to 'vint__10_index11__0__uses' from Difference factor
					vint__10_index11__0__uses_B[index11][0] = IntegerPlusOp.BAverageConditional(42, vint64_B[index11], vint__10_index11__0__uses_B[index11][0]);
					// Message to 'vint__10_index11__0__uses' from Replicate factor
					vint__10_index11__0__uses_F[index11][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__10_index11__0__uses_B[index11], vint__10_F_reduced, 1, vint__10_index11__0__uses_F[index11][1]);
					// Message to 'vString42' from StringOfLength factor
					this.vString42_F[index11] = StringOfLengthOp.StrAverageConditional(vDiscreteChar15, vint__10_index11__0__uses_F[index11][1]);
					// Message to 'vString42_use' from Concat factor
					vString42_use_B[index11] = StringConcatOp.Str1AverageConditional(this.vString44_B[index11], vString41_F[index11]);
					// Message to 'vint__10_index11__0__uses' from StringOfLength factor
					vint__10_index11__0__uses_B[index11][1] = StringOfLengthOp.LengthAverageConditional(vString42_use_B[index11], vDiscreteChar15, vint__10_index11__0__uses_B[index11][1]);
					// Message to 'vint__10_index11__0__uses' from Replicate factor
					vint__10_index11__0__uses_F[index11][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__10_index11__0__uses_B[index11], vint__10_F_reduced, 0, vint__10_index11__0__uses_F[index11][0]);
					// Message to 'vint64' from Difference factor
					vint64_F[index11] = IntegerPlusOp.AAverageConditional(42, vint__10_index11__0__uses_F[index11][0], vint64_F[index11]);
					// Message to 'vString43' from StringOfLength factor
					vString43_F[index11] = StringOfLengthOp.StrAverageConditional(vDiscreteChar15, vint64_F[index11]);
					// Message to 'vString44' from Concat factor
					this.vString44_B[index11] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__5[index11]), vString43_F[index11]);
					// Message to 'vString41' from Concat factor
					vString41_B[index11] = StringConcatOp.Str2AverageConditional(this.vString44_B[index11], this.vString42_F[index11]);
					// Message to 'vChar__10_use' from StringFromArray factor
					vChar__10_use_B[index11] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString41_B[index11], vChar__10_F[index11], vChar__10_use_B[index11]);
					// Message to 'vbool__10_index11__selector_cases_0_uses' from Concat factor
					vbool__10_index11__selector_cases_0_uses_B[index11][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__5[index11], vString44_F[index11], vString43_F[index11]));
					// Message to 'vbool__10_index11__selector_cases_0_uses' from Difference factor
					vbool__10_index11__selector_cases_0_uses_B[index11][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(42, vint64_B[index11], vint__10_index11__0__uses_F[index11][0]));
					// Message to 'vbool__10_index11__selector_cases_0_uses' from Replicate factor
					vbool__10_index11__selector_cases_0_uses_B[index11][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__10_index11__0__uses_B[index11], vint__10_F_reduced, vint__10_index11__0__uses_F[index11]));
					// Message to 'vbool__10_index11__selector_cases_0' from Replicate factor
					vbool__10_index11__selector_cases_0_B[index11] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__10_index11__selector_cases_0_uses_B[index11], vbool__10_index11__selector_cases_0_B[index11]);
					// Message to 'vbool__10_index11__selector_cases' from Copy factor
					vbool__10_index11__selector_cases_B[index11][0] = ArrayHelper.SetTo<Bernoulli>(vbool__10_index11__selector_cases_B[index11][0], vbool__10_index11__selector_cases_0_B[index11]);
					// Message to 'vbool__10_index11__selector_uses' from Cases factor
					vbool__10_index11__selector_uses_B[index11][0] = CasesOp.BAverageConditional(vbool__10_index11__selector_cases_B[index11]);
					vbool__10_index11__selector_uses_B_toDef[index11] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__10_index11__selector_uses_B[index11], vbool__10_index11__selector_uses_B_toDef[index11]);
					vbool__10_index11__selector_uses_F_marginal[index11] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__10_index11__selector_uses_B_toDef[index11], vBernoulli5, vbool__10_index11__selector_uses_F_marginal[index11]);
					// Message to 'vbool__10_index11__selector_uses' from Replicate factor
					vbool__10_index11__selector_uses_F[index11][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__10_index11__selector_rep_B_toDef[index11], vbool__10_index11__selector_uses_F_marginal[index11], 1, vbool__10_index11__selector_uses_F[index11][1]);
					vbool__10_index11__selector_rep_F_marginal[index11] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__10_index11__selector_rep_B_toDef[index11], vbool__10_index11__selector_uses_F[index11][1], vbool__10_index11__selector_rep_F_marginal[index11]);
					for(int index10 = 0; index10<8; index10++) {
						// Message to 'vVector__10__0_' from Char factor
						vVector__10__0__B[index11][index10] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__10_use_B[index11][index10], vVector__10_rep_F[index10][index11], vVector__10__0__B[index11][index10]);
						// Message to 'vVector__10_' from Copy factor
						vVector__10__B[index11][index10][0] = ArrayHelper.SetTo<Dirichlet>(vVector__10__B[index11][index10][0], vVector__10__0__B[index11][index10]);
						// Message to 'vbool__10_index11__selector_rep' from Replicate factor
						vbool__10_index11__selector_rep_F[index11][index10] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__10_index11__selector_rep_B_reduced, vbool__10_index11__selector_rep_F_marginal[index11], index10, vbool__10_index11__selector_rep_F[index11][index10]);
						// Message to 'vVector__10_rep' from EnterPartial factor
						this.vVector__10_rep_B[index10][index11] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__10__B[index11][index10], vbool__10_index11__selector_rep_F[index11][index10], vVector__10_rep_F[index10][index11], new int[1] { 0 }, this.vVector__10_rep_B[index10][index11]);
					}
				}
				for(int index10 = 0; index10<8; index10++) {
					this.vVector__10_rep_B_toDef[index10] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__10_rep_B[index10], this.vVector__10_rep_B_toDef[index10]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index10 = 0; index10<8; index10++) {
				this.vVector__10_marginal_F[index10] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet5.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__10_marginal' from Variable factor
				this.vVector__10_marginal_F[index10] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__10_rep_B_toDef[index10], this.vDirichlet5, this.vVector__10_marginal_F[index10]);
			}
			// Create array for 'vint__10_marginal' Forwards messages.
			this.vint__10_marginal_F = new DistributionRefArray<Discrete,int>(30);
			// Create array for replicates of 'vint__10_index11__0__B'
			Discrete[] vint__10_index11__0__B = new Discrete[30];
			// Create array for replicates of 'vint__10_index11__B'
			Discrete[][] vint__10_index11__B = new Discrete[30][];
			DistributionRefArray<Discrete,int> vint__10_use_B;
			// Create array for 'vint__10_use' Backwards messages.
			vint__10_use_B = new DistributionRefArray<Discrete,int>(30);
			for(int index11 = 0; index11<30; index11++) {
				this.vint__10_marginal_F[index11] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__10_use_B[index11] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				// Message to 'vbool__10_index11__selector_uses' from Replicate factor
				vbool__10_index11__selector_uses_F[index11][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__10_index11__selector_uses_B[index11][2], vbool__10_index11__selector_uses_F_marginal[index11], 2, vbool__10_index11__selector_uses_F[index11][2]);
				// Create array for 'vint__10_index11_' Backwards messages.
				vint__10_index11__B[index11] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__10_index11__B[index11][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				}
				vint__10_index11__0__B[index11] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				// Message to 'vint__10_index11__0_' from Replicate factor
				vint__10_index11__0__B[index11] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__10_index11__0__uses_B[index11], vint__10_index11__0__B[index11]);
				// Message to 'vint__10_index11_' from Copy factor
				vint__10_index11__B[index11][0] = ArrayHelper.SetTo<Discrete>(vint__10_index11__B[index11][0], vint__10_index11__0__B[index11]);
				// Message to 'vint__10_use' from EnterPartial factor
				vint__10_use_B[index11] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__10_index11__B[index11], vbool__10_index11__selector_uses_F[index11][2], vint__10_F_reduced, new int[1] { 0 }, vint__10_use_B[index11]);
				// Message to 'vint__10_marginal' from Variable factor
				this.vint__10_marginal_F[index11] = VariableOp.MarginalAverageConditional<Discrete>(vint__10_use_B[index11], vint__10_F_reduced, this.vint__10_marginal_F[index11]);
			}
			// Create array for 'vbool__10_marginal' Forwards messages.
			this.vbool__10_marginal_F = new DistributionStructArray<Bernoulli,bool>(30);
			for(int index11 = 0; index11<30; index11++) {
				this.vbool__10_marginal_F[index11] = Bernoulli.Uniform();
				// Message to 'vbool__10_marginal' from Variable factor
				this.vbool__10_marginal_F[index11] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__10_index11__selector_uses_B_toDef[index11], vBernoulli5, this.vbool__10_marginal_F[index11]);
			}
			this.Changed_numberOfIterations_vString__5_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__5</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__5(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__5_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__5_isInitialised)) {
				return ;
			}
			for(int index10 = 0; index10<8; index10++) {
				this.vVector__10_rep_B_toDef[index10] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet5);
			}
			for(int index11 = 0; index11<30; index11++) {
				for(int index10 = 0; index10<8; index10++) {
					this.vVector__10_rep_B[index10][index11] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet5.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString42_F[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString44_B[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__5_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__5_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__5</summary>
		private void Changed_vString__5()
		{
			if (this.Changed_vString__5_isDone) {
				return ;
			}
			// Create array for 'vString__5_marginal' Forwards messages.
			this.vString__5_marginal_F = new DistributionRefArray<StringDistribution,string>(30);
			for(int index11 = 0; index11<30; index11++) {
				this.vString__5_marginal_F[index11] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__5_marginal' from DerivedVariable factor
			this.vString__5_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__5, this.vString__5_marginal_F);
			this.Changed_vString__5_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet5 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__10_rep_B_toDef'
			this.vVector__10_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__10_rep_B'
			this.vVector__10_rep_B = new Dirichlet[8][];
			for(int index10 = 0; index10<8; index10++) {
				// Create array for 'vVector__10_rep' Backwards messages.
				this.vVector__10_rep_B[index10] = new Dirichlet[30];
			}
			// Create array for replicates of 'vString42_F'
			this.vString42_F = new StringDistribution[30];
			// Create array for replicates of 'vString44_B'
			this.vString44_B = new StringDistribution[30];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__5_isDone = false;
				}
				this.Changed_numberOfIterations_vString__5_isDone = false;
			}
			this.Changed_vString__5();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__5(initialise);
			this.Changed_numberOfIterations_vString__5(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__5") {
				return this.vString__5;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__5") {
				return this.VString__5Marginal();
			}
			if (variableName=="vVector__10") {
				return this.VVector__10Marginal();
			}
			if (variableName=="vint__10") {
				return this.Vint__10Marginal();
			}
			if (variableName=="vbool__10") {
				return this.Vbool__10Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__5") {
				this.vString__5 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__10' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__10Marginal()
		{
			return this.vbool__10_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__10' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__10Marginal()
		{
			return this.vint__10_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__5' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__5Marginal()
		{
			return this.vString__5_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__10' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__10Marginal()
		{
			return this.vVector__10_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
