// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 10:20 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model32_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__33 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__33</summary>
		public bool Changed_numberOfIterations_vString__33_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__33 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__33</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__33_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__33 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__33</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__33_isInitialised;
		/// <summary>True if Changed_vString__33 has executed. Set this to false to force re-execution of Changed_vString__33</summary>
		public bool Changed_vString__33_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__66'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__66_marginal_F;
		/// <summary>The constant 'vDirichlet33'</summary>
		public Dirichlet vDirichlet33;
		/// <summary>Message to marginal of 'vint__66'</summary>
		public DistributionRefArray<Discrete,int> vint__66_marginal_F;
		/// <summary>Field backing the vString__33 property</summary>
		private string[] vString__33_field;
		/// <summary>Message to marginal of 'vString__33'</summary>
		public DistributionRefArray<StringDistribution,string> vString__33_marginal_F;
		public StringDistribution[] vString266_F;
		public StringDistribution[] vString268_B;
		/// <summary>Message to marginal of 'vVector__66'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__66_marginal_F;
		public Dirichlet[][] vVector__66_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__66_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__33'</summary>
		public string[] vString__33
		{
			get {
				return this.vString__33_field;
			}
			set {
				if ((value!=null)&&(value.Length!=20)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+20)+" was expected for variable \'vString__33\'");
				}
				this.vString__33_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__33_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__33_isInitialised = false;
				this.Changed_numberOfIterations_vString__33_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__33</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__33(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__33_isDone) {
				return ;
			}
			// Create array for 'vVector__66_marginal' Forwards messages.
			this.vVector__66_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__66_rep_F_marginal'
			Dirichlet[] vVector__66_rep_F_marginal = new Dirichlet[8];
			for(int index66 = 0; index66<8; index66++) {
				vVector__66_rep_F_marginal[index66] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet33);
			}
			// Create array for replicates of 'vVector__66_rep_F'
			Dirichlet[][] vVector__66_rep_F = new Dirichlet[8][];
			for(int index66 = 0; index66<8; index66++) {
				// Create array for 'vVector__66_rep' Forwards messages.
				vVector__66_rep_F[index66] = new Dirichlet[20];
			}
			for(int index67 = 0; index67<20; index67++) {
				for(int index66 = 0; index66<8; index66++) {
					vVector__66_rep_F[index66][index67] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet33.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__66_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__66_F = new DistributionStructArray<DiscreteChar,char>[20];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vChar__66' Forwards messages.
				vChar__66_F[index67] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index66 = 0; index66<8; index66++) {
					vChar__66_F[index67][index66] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString265_F'
			StringDistribution[] vString265_F = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString265_F[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString268_F'
			StringDistribution[] vString268_F = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString268_F[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString267_use_B'
			StringDistribution[] vString267_use_B = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString267_use_B[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint372_B'
			Discrete[] vint372_B = new Discrete[20];
			for(int index67 = 0; index67<20; index67++) {
				vint372_B[index67] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			DiscreteChar vDiscreteChar99 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__66_index67__0__uses_B'
			Discrete[][] vint__66_index67__0__uses_B = new Discrete[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vint__66_index67__0__uses' Backwards messages.
				vint__66_index67__0__uses_B[index67] = new Discrete[2];
				vint__66_index67__0__uses_B[index67][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__66_index67__0__uses_B[index67][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vint__66_index67__0__uses_F'
			Discrete[][] vint__66_index67__0__uses_F = new Discrete[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vint__66_index67__0__uses' Forwards messages.
				vint__66_index67__0__uses_F[index67] = new Discrete[2];
				vint__66_index67__0__uses_F[index67][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__66_index67__0__uses_F[index67][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			Discrete vint__66_F_reduced;
			vint__66_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			// Create array for replicates of 'vString266_use_B'
			StringDistribution[] vString266_use_B = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString266_use_B[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint372_F'
			Discrete[] vint372_F = new Discrete[20];
			for(int index67 = 0; index67<20; index67++) {
				vint372_F[index67] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vString267_F'
			StringDistribution[] vString267_F = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString267_F[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString265_B'
			StringDistribution[] vString265_B = new StringDistribution[20];
			for(int index67 = 0; index67<20; index67++) {
				vString265_B[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__66_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__66_use_B = new DistributionStructArray<DiscreteChar,char>[20];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vChar__66_use' Backwards messages.
				vChar__66_use_B[index67] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index66 = 0; index66<8; index66++) {
					vChar__66_use_B[index67][index66] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__66__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__66__0__B = new DistributionRefArray<Dirichlet,Vector>[20];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vVector__66__0_' Backwards messages.
				vVector__66__0__B[index67] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index66 = 0; index66<8; index66++) {
					vVector__66__0__B[index67][index66] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet33.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__66__B'
			Dirichlet[][][] vVector__66__B = new Dirichlet[20][][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vVector__66_' Backwards messages.
				vVector__66__B[index67] = new Dirichlet[8][];
				for(int index66 = 0; index66<8; index66++) {
					// Create array for 'vVector__66_' Backwards messages.
					vVector__66__B[index67][index66] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__66__B[index67][index66][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet33.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__66_index67__selector_cases_0_uses_B'
			Bernoulli[][] vbool__66_index67__selector_cases_0_uses_B = new Bernoulli[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vbool__66_index67__selector_cases_0_uses' Backwards messages.
				vbool__66_index67__selector_cases_0_uses_B[index67] = new Bernoulli[27];
				vbool__66_index67__selector_cases_0_uses_B[index67][25] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][24] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][23] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][22] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][21] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][20] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][19] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][18] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][17] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][16] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][15] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][14] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][11] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][10] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][9] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][8] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][7] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][6] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][5] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][4] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][3] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][2] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][1] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][0] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][12] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][13] = Bernoulli.Uniform();
				vbool__66_index67__selector_cases_0_uses_B[index67][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__66_index67__selector_cases_0_B'
			Bernoulli[] vbool__66_index67__selector_cases_0_B = new Bernoulli[20];
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_cases_0_B[index67] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__66_index67__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__66_index67__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[20];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vbool__66_index67__selector_cases' Backwards messages.
				vbool__66_index67__selector_cases_B[index67] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__66_index67__selector_cases_B[index67][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__66_index67__selector_uses_B'
			Bernoulli[][] vbool__66_index67__selector_uses_B = new Bernoulli[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vbool__66_index67__selector_uses' Backwards messages.
				vbool__66_index67__selector_uses_B[index67] = new Bernoulli[3];
				vbool__66_index67__selector_uses_B[index67][2] = Bernoulli.Uniform();
				vbool__66_index67__selector_uses_B[index67][1] = Bernoulli.Uniform();
				vbool__66_index67__selector_uses_B[index67][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__66_index67__selector_cases_1_B'
			Bernoulli[] vbool__66_index67__selector_cases_1_B = new Bernoulli[20];
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_cases_1_B[index67] = Bernoulli.Uniform();
				// Message to 'vbool__66_index67__selector_cases_1' from StringOfLength factor
				vbool__66_index67__selector_cases_1_B[index67] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar99, 30, this.vString__33[index67]));
				// Message to 'vbool__66_index67__selector_cases' from Copy factor
				vbool__66_index67__selector_cases_B[index67][1] = ArrayHelper.SetTo<Bernoulli>(vbool__66_index67__selector_cases_B[index67][1], vbool__66_index67__selector_cases_1_B[index67]);
			}
			// Create array for replicates of 'vbool__66_index67__selector_uses_B_toDef'
			Bernoulli[] vbool__66_index67__selector_uses_B_toDef = new Bernoulli[20];
			Bernoulli vBernoulli33 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_uses_B_toDef[index67] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli33);
			}
			// Create array for replicates of 'vbool__66_index67__selector_uses_F_marginal'
			Bernoulli[] vbool__66_index67__selector_uses_F_marginal = new Bernoulli[20];
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_uses_F_marginal[index67] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli33);
			}
			// Create array for replicates of 'vbool__66_index67__selector_uses_F'
			Bernoulli[][] vbool__66_index67__selector_uses_F = new Bernoulli[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vbool__66_index67__selector_uses' Forwards messages.
				vbool__66_index67__selector_uses_F[index67] = new Bernoulli[3];
				vbool__66_index67__selector_uses_F[index67][1] = Bernoulli.Uniform();
				vbool__66_index67__selector_uses_F[index67][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__66_index67__selector_rep_B_toDef'
			Bernoulli[] vbool__66_index67__selector_rep_B_toDef = new Bernoulli[20];
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_rep_B_toDef[index67] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__66_index67__selector_uses_F[index67][1]);
			}
			// Create array for replicates of 'vbool__66_index67__selector_rep_F_marginal'
			Bernoulli[] vbool__66_index67__selector_rep_F_marginal = new Bernoulli[20];
			for(int index67 = 0; index67<20; index67++) {
				vbool__66_index67__selector_rep_F_marginal[index67] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__66_index67__selector_uses_F[index67][1]);
			}
			// Create array for replicates of 'vbool__66_index67__selector_rep_F'
			Bernoulli[][] vbool__66_index67__selector_rep_F = new Bernoulli[20][];
			for(int index67 = 0; index67<20; index67++) {
				// Create array for 'vbool__66_index67__selector_rep' Forwards messages.
				vbool__66_index67__selector_rep_F[index67] = new Bernoulli[8];
				for(int index66 = 0; index66<8; index66++) {
					vbool__66_index67__selector_rep_F[index67][index66] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__66_index67__selector_rep_B_reduced = default(Bernoulli);
			vbool__66_index67__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index66 = 0; index66<8; index66++) {
					vVector__66_rep_F_marginal[index66] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__66_rep_B_toDef[index66], this.vDirichlet33, vVector__66_rep_F_marginal[index66]);
				}
				for(int index67 = 0; index67<20; index67++) {
					for(int index66 = 0; index66<8; index66++) {
						// Message to 'vVector__66_rep' from Replicate factor
						vVector__66_rep_F[index66][index67] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__66_rep_B[index66][index67], vVector__66_rep_F_marginal[index66], index67, vVector__66_rep_F[index66][index67]);
						// Message to 'vChar__66' from Char factor
						vChar__66_F[index67][index66] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__66_rep_F[index66][index67]);
					}
					// Message to 'vString265' from StringFromArray factor
					vString265_F[index67] = StringFromArrayOp.StrAverageConditional(vChar__66_F[index67]);
					// Message to 'vString268' from Concat factor
					vString268_F[index67] = StringConcatOp.ConcatAverageConditional(this.vString266_F[index67], vString265_F[index67]);
					// Message to 'vString267_use' from Concat factor
					vString267_use_B[index67] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__33[index67]), vString268_F[index67]);
					// Message to 'vint372' from StringOfLength factor
					vint372_B[index67] = StringOfLengthOp.LengthAverageConditional(vString267_use_B[index67], vDiscreteChar99, vint372_B[index67]);
					// Message to 'vint__66_index67__0__uses' from Difference factor
					vint__66_index67__0__uses_B[index67][0] = IntegerPlusOp.BAverageConditional(22, vint372_B[index67], vint__66_index67__0__uses_B[index67][0]);
					// Message to 'vint__66_index67__0__uses' from Replicate factor
					vint__66_index67__0__uses_F[index67][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__66_index67__0__uses_B[index67], vint__66_F_reduced, 1, vint__66_index67__0__uses_F[index67][1]);
					// Message to 'vString266' from StringOfLength factor
					this.vString266_F[index67] = StringOfLengthOp.StrAverageConditional(vDiscreteChar99, vint__66_index67__0__uses_F[index67][1]);
					// Message to 'vString266_use' from Concat factor
					vString266_use_B[index67] = StringConcatOp.Str1AverageConditional(this.vString268_B[index67], vString265_F[index67]);
					// Message to 'vint__66_index67__0__uses' from StringOfLength factor
					vint__66_index67__0__uses_B[index67][1] = StringOfLengthOp.LengthAverageConditional(vString266_use_B[index67], vDiscreteChar99, vint__66_index67__0__uses_B[index67][1]);
					// Message to 'vint__66_index67__0__uses' from Replicate factor
					vint__66_index67__0__uses_F[index67][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__66_index67__0__uses_B[index67], vint__66_F_reduced, 0, vint__66_index67__0__uses_F[index67][0]);
					// Message to 'vint372' from Difference factor
					vint372_F[index67] = IntegerPlusOp.AAverageConditional(22, vint__66_index67__0__uses_F[index67][0], vint372_F[index67]);
					// Message to 'vString267' from StringOfLength factor
					vString267_F[index67] = StringOfLengthOp.StrAverageConditional(vDiscreteChar99, vint372_F[index67]);
					// Message to 'vString268' from Concat factor
					this.vString268_B[index67] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__33[index67]), vString267_F[index67]);
					// Message to 'vString265' from Concat factor
					vString265_B[index67] = StringConcatOp.Str2AverageConditional(this.vString268_B[index67], this.vString266_F[index67]);
					// Message to 'vChar__66_use' from StringFromArray factor
					vChar__66_use_B[index67] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString265_B[index67], vChar__66_F[index67], vChar__66_use_B[index67]);
					// Message to 'vbool__66_index67__selector_cases_0_uses' from Concat factor
					vbool__66_index67__selector_cases_0_uses_B[index67][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__33[index67], vString268_F[index67], vString267_F[index67]));
					// Message to 'vbool__66_index67__selector_cases_0_uses' from Difference factor
					vbool__66_index67__selector_cases_0_uses_B[index67][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(22, vint372_B[index67], vint__66_index67__0__uses_F[index67][0]));
					// Message to 'vbool__66_index67__selector_cases_0_uses' from Replicate factor
					vbool__66_index67__selector_cases_0_uses_B[index67][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__66_index67__0__uses_B[index67], vint__66_F_reduced, vint__66_index67__0__uses_F[index67]));
					// Message to 'vbool__66_index67__selector_cases_0' from Replicate factor
					vbool__66_index67__selector_cases_0_B[index67] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__66_index67__selector_cases_0_uses_B[index67], vbool__66_index67__selector_cases_0_B[index67]);
					// Message to 'vbool__66_index67__selector_cases' from Copy factor
					vbool__66_index67__selector_cases_B[index67][0] = ArrayHelper.SetTo<Bernoulli>(vbool__66_index67__selector_cases_B[index67][0], vbool__66_index67__selector_cases_0_B[index67]);
					// Message to 'vbool__66_index67__selector_uses' from Cases factor
					vbool__66_index67__selector_uses_B[index67][0] = CasesOp.BAverageConditional(vbool__66_index67__selector_cases_B[index67]);
					vbool__66_index67__selector_uses_B_toDef[index67] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__66_index67__selector_uses_B[index67], vbool__66_index67__selector_uses_B_toDef[index67]);
					vbool__66_index67__selector_uses_F_marginal[index67] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__66_index67__selector_uses_B_toDef[index67], vBernoulli33, vbool__66_index67__selector_uses_F_marginal[index67]);
					// Message to 'vbool__66_index67__selector_uses' from Replicate factor
					vbool__66_index67__selector_uses_F[index67][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__66_index67__selector_rep_B_toDef[index67], vbool__66_index67__selector_uses_F_marginal[index67], 1, vbool__66_index67__selector_uses_F[index67][1]);
					vbool__66_index67__selector_rep_F_marginal[index67] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__66_index67__selector_rep_B_toDef[index67], vbool__66_index67__selector_uses_F[index67][1], vbool__66_index67__selector_rep_F_marginal[index67]);
					for(int index66 = 0; index66<8; index66++) {
						// Message to 'vVector__66__0_' from Char factor
						vVector__66__0__B[index67][index66] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__66_use_B[index67][index66], vVector__66_rep_F[index66][index67], vVector__66__0__B[index67][index66]);
						// Message to 'vVector__66_' from Copy factor
						vVector__66__B[index67][index66][0] = ArrayHelper.SetTo<Dirichlet>(vVector__66__B[index67][index66][0], vVector__66__0__B[index67][index66]);
						// Message to 'vbool__66_index67__selector_rep' from Replicate factor
						vbool__66_index67__selector_rep_F[index67][index66] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__66_index67__selector_rep_B_reduced, vbool__66_index67__selector_rep_F_marginal[index67], index66, vbool__66_index67__selector_rep_F[index67][index66]);
						// Message to 'vVector__66_rep' from EnterPartial factor
						this.vVector__66_rep_B[index66][index67] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__66__B[index67][index66], vbool__66_index67__selector_rep_F[index67][index66], vVector__66_rep_F[index66][index67], new int[1] { 0 }, this.vVector__66_rep_B[index66][index67]);
					}
				}
				for(int index66 = 0; index66<8; index66++) {
					this.vVector__66_rep_B_toDef[index66] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__66_rep_B[index66], this.vVector__66_rep_B_toDef[index66]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index66 = 0; index66<8; index66++) {
				this.vVector__66_marginal_F[index66] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet33.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__66_marginal' from Variable factor
				this.vVector__66_marginal_F[index66] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__66_rep_B_toDef[index66], this.vDirichlet33, this.vVector__66_marginal_F[index66]);
			}
			// Create array for 'vint__66_marginal' Forwards messages.
			this.vint__66_marginal_F = new DistributionRefArray<Discrete,int>(20);
			// Create array for replicates of 'vint__66_index67__0__B'
			Discrete[] vint__66_index67__0__B = new Discrete[20];
			// Create array for replicates of 'vint__66_index67__B'
			Discrete[][] vint__66_index67__B = new Discrete[20][];
			DistributionRefArray<Discrete,int> vint__66_use_B;
			// Create array for 'vint__66_use' Backwards messages.
			vint__66_use_B = new DistributionRefArray<Discrete,int>(20);
			for(int index67 = 0; index67<20; index67++) {
				this.vint__66_marginal_F[index67] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__66_use_B[index67] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vbool__66_index67__selector_uses' from Replicate factor
				vbool__66_index67__selector_uses_F[index67][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__66_index67__selector_uses_B[index67][2], vbool__66_index67__selector_uses_F_marginal[index67], 2, vbool__66_index67__selector_uses_F[index67][2]);
				// Create array for 'vint__66_index67_' Backwards messages.
				vint__66_index67__B[index67] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__66_index67__B[index67][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				}
				vint__66_index67__0__B[index67] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vint__66_index67__0_' from Replicate factor
				vint__66_index67__0__B[index67] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__66_index67__0__uses_B[index67], vint__66_index67__0__B[index67]);
				// Message to 'vint__66_index67_' from Copy factor
				vint__66_index67__B[index67][0] = ArrayHelper.SetTo<Discrete>(vint__66_index67__B[index67][0], vint__66_index67__0__B[index67]);
				// Message to 'vint__66_use' from EnterPartial factor
				vint__66_use_B[index67] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__66_index67__B[index67], vbool__66_index67__selector_uses_F[index67][2], vint__66_F_reduced, new int[1] { 0 }, vint__66_use_B[index67]);
				// Message to 'vint__66_marginal' from Variable factor
				this.vint__66_marginal_F[index67] = VariableOp.MarginalAverageConditional<Discrete>(vint__66_use_B[index67], vint__66_F_reduced, this.vint__66_marginal_F[index67]);
			}
			// Create array for 'vbool__66_marginal' Forwards messages.
			this.vbool__66_marginal_F = new DistributionStructArray<Bernoulli,bool>(20);
			for(int index67 = 0; index67<20; index67++) {
				this.vbool__66_marginal_F[index67] = Bernoulli.Uniform();
				// Message to 'vbool__66_marginal' from Variable factor
				this.vbool__66_marginal_F[index67] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__66_index67__selector_uses_B_toDef[index67], vBernoulli33, this.vbool__66_marginal_F[index67]);
			}
			this.Changed_numberOfIterations_vString__33_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__33</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__33(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__33_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__33_isInitialised)) {
				return ;
			}
			for(int index66 = 0; index66<8; index66++) {
				this.vVector__66_rep_B_toDef[index66] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet33);
			}
			for(int index67 = 0; index67<20; index67++) {
				for(int index66 = 0; index66<8; index66++) {
					this.vVector__66_rep_B[index66][index67] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet33.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString266_F[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString268_B[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__33_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__33_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__33</summary>
		private void Changed_vString__33()
		{
			if (this.Changed_vString__33_isDone) {
				return ;
			}
			// Create array for 'vString__33_marginal' Forwards messages.
			this.vString__33_marginal_F = new DistributionRefArray<StringDistribution,string>(20);
			for(int index67 = 0; index67<20; index67++) {
				this.vString__33_marginal_F[index67] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__33_marginal' from DerivedVariable factor
			this.vString__33_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__33, this.vString__33_marginal_F);
			this.Changed_vString__33_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet33 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__66_rep_B_toDef'
			this.vVector__66_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__66_rep_B'
			this.vVector__66_rep_B = new Dirichlet[8][];
			for(int index66 = 0; index66<8; index66++) {
				// Create array for 'vVector__66_rep' Backwards messages.
				this.vVector__66_rep_B[index66] = new Dirichlet[20];
			}
			// Create array for replicates of 'vString266_F'
			this.vString266_F = new StringDistribution[20];
			// Create array for replicates of 'vString268_B'
			this.vString268_B = new StringDistribution[20];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__33_isDone = false;
				}
				this.Changed_numberOfIterations_vString__33_isDone = false;
			}
			this.Changed_vString__33();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__33(initialise);
			this.Changed_numberOfIterations_vString__33(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__33") {
				return this.vString__33;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__33") {
				return this.VString__33Marginal();
			}
			if (variableName=="vVector__66") {
				return this.VVector__66Marginal();
			}
			if (variableName=="vint__66") {
				return this.Vint__66Marginal();
			}
			if (variableName=="vbool__66") {
				return this.Vbool__66Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__33") {
				this.vString__33 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__66' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__66Marginal()
		{
			return this.vbool__66_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__66' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__66Marginal()
		{
			return this.vint__66_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__33' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__33Marginal()
		{
			return this.vString__33_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__66' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__66Marginal()
		{
			return this.vVector__66_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
