// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 10:20 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model29_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__30 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__30</summary>
		public bool Changed_numberOfIterations_vString__30_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__30 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__30</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__30_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__30 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__30</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__30_isInitialised;
		/// <summary>True if Changed_vString__30 has executed. Set this to false to force re-execution of Changed_vString__30</summary>
		public bool Changed_vString__30_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__60'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__60_marginal_F;
		/// <summary>The constant 'vDirichlet30'</summary>
		public Dirichlet vDirichlet30;
		/// <summary>Message to marginal of 'vint__60'</summary>
		public DistributionRefArray<Discrete,int> vint__60_marginal_F;
		/// <summary>Field backing the vString__30 property</summary>
		private string[] vString__30_field;
		/// <summary>Message to marginal of 'vString__30'</summary>
		public DistributionRefArray<StringDistribution,string> vString__30_marginal_F;
		public StringDistribution[] vString242_F;
		public StringDistribution[] vString244_B;
		/// <summary>Message to marginal of 'vVector__60'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__60_marginal_F;
		public Dirichlet[][] vVector__60_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__60_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__30'</summary>
		public string[] vString__30
		{
			get {
				return this.vString__30_field;
			}
			set {
				if ((value!=null)&&(value.Length!=20)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+20)+" was expected for variable \'vString__30\'");
				}
				this.vString__30_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__30_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__30_isInitialised = false;
				this.Changed_numberOfIterations_vString__30_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__30</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__30(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__30_isDone) {
				return ;
			}
			// Create array for 'vVector__60_marginal' Forwards messages.
			this.vVector__60_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__60_rep_F_marginal'
			Dirichlet[] vVector__60_rep_F_marginal = new Dirichlet[8];
			for(int index60 = 0; index60<8; index60++) {
				vVector__60_rep_F_marginal[index60] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet30);
			}
			// Create array for replicates of 'vVector__60_rep_F'
			Dirichlet[][] vVector__60_rep_F = new Dirichlet[8][];
			for(int index60 = 0; index60<8; index60++) {
				// Create array for 'vVector__60_rep' Forwards messages.
				vVector__60_rep_F[index60] = new Dirichlet[20];
			}
			for(int index61 = 0; index61<20; index61++) {
				for(int index60 = 0; index60<8; index60++) {
					vVector__60_rep_F[index60][index61] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet30.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__60_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__60_F = new DistributionStructArray<DiscreteChar,char>[20];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vChar__60' Forwards messages.
				vChar__60_F[index61] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index60 = 0; index60<8; index60++) {
					vChar__60_F[index61][index60] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString241_F'
			StringDistribution[] vString241_F = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString241_F[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString244_F'
			StringDistribution[] vString244_F = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString244_F[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString243_use_B'
			StringDistribution[] vString243_use_B = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString243_use_B[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint339_B'
			Discrete[] vint339_B = new Discrete[20];
			for(int index61 = 0; index61<20; index61++) {
				vint339_B[index61] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			DiscreteChar vDiscreteChar90 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__60_index61__0__uses_B'
			Discrete[][] vint__60_index61__0__uses_B = new Discrete[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vint__60_index61__0__uses' Backwards messages.
				vint__60_index61__0__uses_B[index61] = new Discrete[2];
				vint__60_index61__0__uses_B[index61][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__60_index61__0__uses_B[index61][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vint__60_index61__0__uses_F'
			Discrete[][] vint__60_index61__0__uses_F = new Discrete[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vint__60_index61__0__uses' Forwards messages.
				vint__60_index61__0__uses_F[index61] = new Discrete[2];
				vint__60_index61__0__uses_F[index61][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__60_index61__0__uses_F[index61][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			Discrete vint__60_F_reduced;
			vint__60_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			// Create array for replicates of 'vString242_use_B'
			StringDistribution[] vString242_use_B = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString242_use_B[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint339_F'
			Discrete[] vint339_F = new Discrete[20];
			for(int index61 = 0; index61<20; index61++) {
				vint339_F[index61] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vString243_F'
			StringDistribution[] vString243_F = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString243_F[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString241_B'
			StringDistribution[] vString241_B = new StringDistribution[20];
			for(int index61 = 0; index61<20; index61++) {
				vString241_B[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__60_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__60_use_B = new DistributionStructArray<DiscreteChar,char>[20];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vChar__60_use' Backwards messages.
				vChar__60_use_B[index61] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index60 = 0; index60<8; index60++) {
					vChar__60_use_B[index61][index60] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__60__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__60__0__B = new DistributionRefArray<Dirichlet,Vector>[20];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vVector__60__0_' Backwards messages.
				vVector__60__0__B[index61] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index60 = 0; index60<8; index60++) {
					vVector__60__0__B[index61][index60] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet30.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__60__B'
			Dirichlet[][][] vVector__60__B = new Dirichlet[20][][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vVector__60_' Backwards messages.
				vVector__60__B[index61] = new Dirichlet[8][];
				for(int index60 = 0; index60<8; index60++) {
					// Create array for 'vVector__60_' Backwards messages.
					vVector__60__B[index61][index60] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__60__B[index61][index60][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet30.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__60_index61__selector_cases_0_uses_B'
			Bernoulli[][] vbool__60_index61__selector_cases_0_uses_B = new Bernoulli[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vbool__60_index61__selector_cases_0_uses' Backwards messages.
				vbool__60_index61__selector_cases_0_uses_B[index61] = new Bernoulli[27];
				vbool__60_index61__selector_cases_0_uses_B[index61][25] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][24] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][23] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][22] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][21] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][20] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][19] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][18] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][17] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][16] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][15] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][14] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][11] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][10] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][9] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][8] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][7] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][6] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][5] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][4] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][3] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][2] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][1] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][0] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][12] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][13] = Bernoulli.Uniform();
				vbool__60_index61__selector_cases_0_uses_B[index61][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__60_index61__selector_cases_0_B'
			Bernoulli[] vbool__60_index61__selector_cases_0_B = new Bernoulli[20];
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_cases_0_B[index61] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__60_index61__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__60_index61__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[20];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vbool__60_index61__selector_cases' Backwards messages.
				vbool__60_index61__selector_cases_B[index61] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__60_index61__selector_cases_B[index61][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__60_index61__selector_uses_B'
			Bernoulli[][] vbool__60_index61__selector_uses_B = new Bernoulli[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vbool__60_index61__selector_uses' Backwards messages.
				vbool__60_index61__selector_uses_B[index61] = new Bernoulli[3];
				vbool__60_index61__selector_uses_B[index61][2] = Bernoulli.Uniform();
				vbool__60_index61__selector_uses_B[index61][1] = Bernoulli.Uniform();
				vbool__60_index61__selector_uses_B[index61][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__60_index61__selector_cases_1_B'
			Bernoulli[] vbool__60_index61__selector_cases_1_B = new Bernoulli[20];
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_cases_1_B[index61] = Bernoulli.Uniform();
				// Message to 'vbool__60_index61__selector_cases_1' from StringOfLength factor
				vbool__60_index61__selector_cases_1_B[index61] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar90, 30, this.vString__30[index61]));
				// Message to 'vbool__60_index61__selector_cases' from Copy factor
				vbool__60_index61__selector_cases_B[index61][1] = ArrayHelper.SetTo<Bernoulli>(vbool__60_index61__selector_cases_B[index61][1], vbool__60_index61__selector_cases_1_B[index61]);
			}
			// Create array for replicates of 'vbool__60_index61__selector_uses_B_toDef'
			Bernoulli[] vbool__60_index61__selector_uses_B_toDef = new Bernoulli[20];
			Bernoulli vBernoulli30 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_uses_B_toDef[index61] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli30);
			}
			// Create array for replicates of 'vbool__60_index61__selector_uses_F_marginal'
			Bernoulli[] vbool__60_index61__selector_uses_F_marginal = new Bernoulli[20];
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_uses_F_marginal[index61] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli30);
			}
			// Create array for replicates of 'vbool__60_index61__selector_uses_F'
			Bernoulli[][] vbool__60_index61__selector_uses_F = new Bernoulli[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vbool__60_index61__selector_uses' Forwards messages.
				vbool__60_index61__selector_uses_F[index61] = new Bernoulli[3];
				vbool__60_index61__selector_uses_F[index61][1] = Bernoulli.Uniform();
				vbool__60_index61__selector_uses_F[index61][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__60_index61__selector_rep_B_toDef'
			Bernoulli[] vbool__60_index61__selector_rep_B_toDef = new Bernoulli[20];
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_rep_B_toDef[index61] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__60_index61__selector_uses_F[index61][1]);
			}
			// Create array for replicates of 'vbool__60_index61__selector_rep_F_marginal'
			Bernoulli[] vbool__60_index61__selector_rep_F_marginal = new Bernoulli[20];
			for(int index61 = 0; index61<20; index61++) {
				vbool__60_index61__selector_rep_F_marginal[index61] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__60_index61__selector_uses_F[index61][1]);
			}
			// Create array for replicates of 'vbool__60_index61__selector_rep_F'
			Bernoulli[][] vbool__60_index61__selector_rep_F = new Bernoulli[20][];
			for(int index61 = 0; index61<20; index61++) {
				// Create array for 'vbool__60_index61__selector_rep' Forwards messages.
				vbool__60_index61__selector_rep_F[index61] = new Bernoulli[8];
				for(int index60 = 0; index60<8; index60++) {
					vbool__60_index61__selector_rep_F[index61][index60] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__60_index61__selector_rep_B_reduced = default(Bernoulli);
			vbool__60_index61__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index60 = 0; index60<8; index60++) {
					vVector__60_rep_F_marginal[index60] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__60_rep_B_toDef[index60], this.vDirichlet30, vVector__60_rep_F_marginal[index60]);
				}
				for(int index61 = 0; index61<20; index61++) {
					for(int index60 = 0; index60<8; index60++) {
						// Message to 'vVector__60_rep' from Replicate factor
						vVector__60_rep_F[index60][index61] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__60_rep_B[index60][index61], vVector__60_rep_F_marginal[index60], index61, vVector__60_rep_F[index60][index61]);
						// Message to 'vChar__60' from Char factor
						vChar__60_F[index61][index60] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__60_rep_F[index60][index61]);
					}
					// Message to 'vString241' from StringFromArray factor
					vString241_F[index61] = StringFromArrayOp.StrAverageConditional(vChar__60_F[index61]);
					// Message to 'vString244' from Concat factor
					vString244_F[index61] = StringConcatOp.ConcatAverageConditional(this.vString242_F[index61], vString241_F[index61]);
					// Message to 'vString243_use' from Concat factor
					vString243_use_B[index61] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__30[index61]), vString244_F[index61]);
					// Message to 'vint339' from StringOfLength factor
					vint339_B[index61] = StringOfLengthOp.LengthAverageConditional(vString243_use_B[index61], vDiscreteChar90, vint339_B[index61]);
					// Message to 'vint__60_index61__0__uses' from Difference factor
					vint__60_index61__0__uses_B[index61][0] = IntegerPlusOp.BAverageConditional(22, vint339_B[index61], vint__60_index61__0__uses_B[index61][0]);
					// Message to 'vint__60_index61__0__uses' from Replicate factor
					vint__60_index61__0__uses_F[index61][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__60_index61__0__uses_B[index61], vint__60_F_reduced, 1, vint__60_index61__0__uses_F[index61][1]);
					// Message to 'vString242' from StringOfLength factor
					this.vString242_F[index61] = StringOfLengthOp.StrAverageConditional(vDiscreteChar90, vint__60_index61__0__uses_F[index61][1]);
					// Message to 'vString242_use' from Concat factor
					vString242_use_B[index61] = StringConcatOp.Str1AverageConditional(this.vString244_B[index61], vString241_F[index61]);
					// Message to 'vint__60_index61__0__uses' from StringOfLength factor
					vint__60_index61__0__uses_B[index61][1] = StringOfLengthOp.LengthAverageConditional(vString242_use_B[index61], vDiscreteChar90, vint__60_index61__0__uses_B[index61][1]);
					// Message to 'vint__60_index61__0__uses' from Replicate factor
					vint__60_index61__0__uses_F[index61][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__60_index61__0__uses_B[index61], vint__60_F_reduced, 0, vint__60_index61__0__uses_F[index61][0]);
					// Message to 'vint339' from Difference factor
					vint339_F[index61] = IntegerPlusOp.AAverageConditional(22, vint__60_index61__0__uses_F[index61][0], vint339_F[index61]);
					// Message to 'vString243' from StringOfLength factor
					vString243_F[index61] = StringOfLengthOp.StrAverageConditional(vDiscreteChar90, vint339_F[index61]);
					// Message to 'vString244' from Concat factor
					this.vString244_B[index61] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__30[index61]), vString243_F[index61]);
					// Message to 'vString241' from Concat factor
					vString241_B[index61] = StringConcatOp.Str2AverageConditional(this.vString244_B[index61], this.vString242_F[index61]);
					// Message to 'vChar__60_use' from StringFromArray factor
					vChar__60_use_B[index61] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString241_B[index61], vChar__60_F[index61], vChar__60_use_B[index61]);
					// Message to 'vbool__60_index61__selector_cases_0_uses' from Concat factor
					vbool__60_index61__selector_cases_0_uses_B[index61][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__30[index61], vString244_F[index61], vString243_F[index61]));
					// Message to 'vbool__60_index61__selector_cases_0_uses' from Difference factor
					vbool__60_index61__selector_cases_0_uses_B[index61][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(22, vint339_B[index61], vint__60_index61__0__uses_F[index61][0]));
					// Message to 'vbool__60_index61__selector_cases_0_uses' from Replicate factor
					vbool__60_index61__selector_cases_0_uses_B[index61][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__60_index61__0__uses_B[index61], vint__60_F_reduced, vint__60_index61__0__uses_F[index61]));
					// Message to 'vbool__60_index61__selector_cases_0' from Replicate factor
					vbool__60_index61__selector_cases_0_B[index61] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__60_index61__selector_cases_0_uses_B[index61], vbool__60_index61__selector_cases_0_B[index61]);
					// Message to 'vbool__60_index61__selector_cases' from Copy factor
					vbool__60_index61__selector_cases_B[index61][0] = ArrayHelper.SetTo<Bernoulli>(vbool__60_index61__selector_cases_B[index61][0], vbool__60_index61__selector_cases_0_B[index61]);
					// Message to 'vbool__60_index61__selector_uses' from Cases factor
					vbool__60_index61__selector_uses_B[index61][0] = CasesOp.BAverageConditional(vbool__60_index61__selector_cases_B[index61]);
					vbool__60_index61__selector_uses_B_toDef[index61] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__60_index61__selector_uses_B[index61], vbool__60_index61__selector_uses_B_toDef[index61]);
					vbool__60_index61__selector_uses_F_marginal[index61] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__60_index61__selector_uses_B_toDef[index61], vBernoulli30, vbool__60_index61__selector_uses_F_marginal[index61]);
					// Message to 'vbool__60_index61__selector_uses' from Replicate factor
					vbool__60_index61__selector_uses_F[index61][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__60_index61__selector_rep_B_toDef[index61], vbool__60_index61__selector_uses_F_marginal[index61], 1, vbool__60_index61__selector_uses_F[index61][1]);
					vbool__60_index61__selector_rep_F_marginal[index61] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__60_index61__selector_rep_B_toDef[index61], vbool__60_index61__selector_uses_F[index61][1], vbool__60_index61__selector_rep_F_marginal[index61]);
					for(int index60 = 0; index60<8; index60++) {
						// Message to 'vVector__60__0_' from Char factor
						vVector__60__0__B[index61][index60] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__60_use_B[index61][index60], vVector__60_rep_F[index60][index61], vVector__60__0__B[index61][index60]);
						// Message to 'vVector__60_' from Copy factor
						vVector__60__B[index61][index60][0] = ArrayHelper.SetTo<Dirichlet>(vVector__60__B[index61][index60][0], vVector__60__0__B[index61][index60]);
						// Message to 'vbool__60_index61__selector_rep' from Replicate factor
						vbool__60_index61__selector_rep_F[index61][index60] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__60_index61__selector_rep_B_reduced, vbool__60_index61__selector_rep_F_marginal[index61], index60, vbool__60_index61__selector_rep_F[index61][index60]);
						// Message to 'vVector__60_rep' from EnterPartial factor
						this.vVector__60_rep_B[index60][index61] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__60__B[index61][index60], vbool__60_index61__selector_rep_F[index61][index60], vVector__60_rep_F[index60][index61], new int[1] { 0 }, this.vVector__60_rep_B[index60][index61]);
					}
				}
				for(int index60 = 0; index60<8; index60++) {
					this.vVector__60_rep_B_toDef[index60] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__60_rep_B[index60], this.vVector__60_rep_B_toDef[index60]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index60 = 0; index60<8; index60++) {
				this.vVector__60_marginal_F[index60] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet30.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__60_marginal' from Variable factor
				this.vVector__60_marginal_F[index60] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__60_rep_B_toDef[index60], this.vDirichlet30, this.vVector__60_marginal_F[index60]);
			}
			// Create array for 'vint__60_marginal' Forwards messages.
			this.vint__60_marginal_F = new DistributionRefArray<Discrete,int>(20);
			// Create array for replicates of 'vint__60_index61__0__B'
			Discrete[] vint__60_index61__0__B = new Discrete[20];
			// Create array for replicates of 'vint__60_index61__B'
			Discrete[][] vint__60_index61__B = new Discrete[20][];
			DistributionRefArray<Discrete,int> vint__60_use_B;
			// Create array for 'vint__60_use' Backwards messages.
			vint__60_use_B = new DistributionRefArray<Discrete,int>(20);
			for(int index61 = 0; index61<20; index61++) {
				this.vint__60_marginal_F[index61] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__60_use_B[index61] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vbool__60_index61__selector_uses' from Replicate factor
				vbool__60_index61__selector_uses_F[index61][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__60_index61__selector_uses_B[index61][2], vbool__60_index61__selector_uses_F_marginal[index61], 2, vbool__60_index61__selector_uses_F[index61][2]);
				// Create array for 'vint__60_index61_' Backwards messages.
				vint__60_index61__B[index61] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__60_index61__B[index61][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				}
				vint__60_index61__0__B[index61] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vint__60_index61__0_' from Replicate factor
				vint__60_index61__0__B[index61] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__60_index61__0__uses_B[index61], vint__60_index61__0__B[index61]);
				// Message to 'vint__60_index61_' from Copy factor
				vint__60_index61__B[index61][0] = ArrayHelper.SetTo<Discrete>(vint__60_index61__B[index61][0], vint__60_index61__0__B[index61]);
				// Message to 'vint__60_use' from EnterPartial factor
				vint__60_use_B[index61] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__60_index61__B[index61], vbool__60_index61__selector_uses_F[index61][2], vint__60_F_reduced, new int[1] { 0 }, vint__60_use_B[index61]);
				// Message to 'vint__60_marginal' from Variable factor
				this.vint__60_marginal_F[index61] = VariableOp.MarginalAverageConditional<Discrete>(vint__60_use_B[index61], vint__60_F_reduced, this.vint__60_marginal_F[index61]);
			}
			// Create array for 'vbool__60_marginal' Forwards messages.
			this.vbool__60_marginal_F = new DistributionStructArray<Bernoulli,bool>(20);
			for(int index61 = 0; index61<20; index61++) {
				this.vbool__60_marginal_F[index61] = Bernoulli.Uniform();
				// Message to 'vbool__60_marginal' from Variable factor
				this.vbool__60_marginal_F[index61] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__60_index61__selector_uses_B_toDef[index61], vBernoulli30, this.vbool__60_marginal_F[index61]);
			}
			this.Changed_numberOfIterations_vString__30_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__30</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__30(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__30_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__30_isInitialised)) {
				return ;
			}
			for(int index60 = 0; index60<8; index60++) {
				this.vVector__60_rep_B_toDef[index60] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet30);
			}
			for(int index61 = 0; index61<20; index61++) {
				for(int index60 = 0; index60<8; index60++) {
					this.vVector__60_rep_B[index60][index61] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet30.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString242_F[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString244_B[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__30_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__30_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__30</summary>
		private void Changed_vString__30()
		{
			if (this.Changed_vString__30_isDone) {
				return ;
			}
			// Create array for 'vString__30_marginal' Forwards messages.
			this.vString__30_marginal_F = new DistributionRefArray<StringDistribution,string>(20);
			for(int index61 = 0; index61<20; index61++) {
				this.vString__30_marginal_F[index61] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__30_marginal' from DerivedVariable factor
			this.vString__30_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__30, this.vString__30_marginal_F);
			this.Changed_vString__30_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet30 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__60_rep_B_toDef'
			this.vVector__60_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__60_rep_B'
			this.vVector__60_rep_B = new Dirichlet[8][];
			for(int index60 = 0; index60<8; index60++) {
				// Create array for 'vVector__60_rep' Backwards messages.
				this.vVector__60_rep_B[index60] = new Dirichlet[20];
			}
			// Create array for replicates of 'vString242_F'
			this.vString242_F = new StringDistribution[20];
			// Create array for replicates of 'vString244_B'
			this.vString244_B = new StringDistribution[20];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__30_isDone = false;
				}
				this.Changed_numberOfIterations_vString__30_isDone = false;
			}
			this.Changed_vString__30();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__30(initialise);
			this.Changed_numberOfIterations_vString__30(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__30") {
				return this.vString__30;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__30") {
				return this.VString__30Marginal();
			}
			if (variableName=="vVector__60") {
				return this.VVector__60Marginal();
			}
			if (variableName=="vint__60") {
				return this.Vint__60Marginal();
			}
			if (variableName=="vbool__60") {
				return this.Vbool__60Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__30") {
				this.vString__30 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__60' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__60Marginal()
		{
			return this.vbool__60_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__60' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__60Marginal()
		{
			return this.vint__60_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__30' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__30Marginal()
		{
			return this.vString__30_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__60' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__60Marginal()
		{
			return this.vVector__60_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
