// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 10:20 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model26_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__27 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__27</summary>
		public bool Changed_numberOfIterations_vString__27_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__27 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__27</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__27_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__27 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__27</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__27_isInitialised;
		/// <summary>True if Changed_vString__27 has executed. Set this to false to force re-execution of Changed_vString__27</summary>
		public bool Changed_vString__27_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__54'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__54_marginal_F;
		/// <summary>The constant 'vDirichlet27'</summary>
		public Dirichlet vDirichlet27;
		/// <summary>Message to marginal of 'vint__54'</summary>
		public DistributionRefArray<Discrete,int> vint__54_marginal_F;
		/// <summary>Field backing the vString__27 property</summary>
		private string[] vString__27_field;
		/// <summary>Message to marginal of 'vString__27'</summary>
		public DistributionRefArray<StringDistribution,string> vString__27_marginal_F;
		public StringDistribution[] vString218_F;
		public StringDistribution[] vString220_B;
		/// <summary>Message to marginal of 'vVector__54'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__54_marginal_F;
		public Dirichlet[][] vVector__54_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__54_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__27'</summary>
		public string[] vString__27
		{
			get {
				return this.vString__27_field;
			}
			set {
				if ((value!=null)&&(value.Length!=10)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+10)+" was expected for variable \'vString__27\'");
				}
				this.vString__27_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__27_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__27_isInitialised = false;
				this.Changed_numberOfIterations_vString__27_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__27</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__27(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__27_isDone) {
				return ;
			}
			// Create array for 'vVector__54_marginal' Forwards messages.
			this.vVector__54_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__54_rep_F_marginal'
			Dirichlet[] vVector__54_rep_F_marginal = new Dirichlet[8];
			for(int index54 = 0; index54<8; index54++) {
				vVector__54_rep_F_marginal[index54] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet27);
			}
			// Create array for replicates of 'vVector__54_rep_F'
			Dirichlet[][] vVector__54_rep_F = new Dirichlet[8][];
			for(int index54 = 0; index54<8; index54++) {
				// Create array for 'vVector__54_rep' Forwards messages.
				vVector__54_rep_F[index54] = new Dirichlet[10];
			}
			for(int index55 = 0; index55<10; index55++) {
				for(int index54 = 0; index54<8; index54++) {
					vVector__54_rep_F[index54][index55] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet27.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__54_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__54_F = new DistributionStructArray<DiscreteChar,char>[10];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vChar__54' Forwards messages.
				vChar__54_F[index55] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index54 = 0; index54<8; index54++) {
					vChar__54_F[index55][index54] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString217_F'
			StringDistribution[] vString217_F = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString217_F[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString220_F'
			StringDistribution[] vString220_F = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString220_F[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString219_use_B'
			StringDistribution[] vString219_use_B = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString219_use_B[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint306_B'
			Discrete[] vint306_B = new Discrete[10];
			for(int index55 = 0; index55<10; index55++) {
				vint306_B[index55] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			DiscreteChar vDiscreteChar81 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__54_index55__0__uses_B'
			Discrete[][] vint__54_index55__0__uses_B = new Discrete[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vint__54_index55__0__uses' Backwards messages.
				vint__54_index55__0__uses_B[index55] = new Discrete[2];
				vint__54_index55__0__uses_B[index55][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__54_index55__0__uses_B[index55][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vint__54_index55__0__uses_F'
			Discrete[][] vint__54_index55__0__uses_F = new Discrete[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vint__54_index55__0__uses' Forwards messages.
				vint__54_index55__0__uses_F[index55] = new Discrete[2];
				vint__54_index55__0__uses_F[index55][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__54_index55__0__uses_F[index55][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			Discrete vint__54_F_reduced;
			vint__54_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			// Create array for replicates of 'vString218_use_B'
			StringDistribution[] vString218_use_B = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString218_use_B[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint306_F'
			Discrete[] vint306_F = new Discrete[10];
			for(int index55 = 0; index55<10; index55++) {
				vint306_F[index55] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
			}
			// Create array for replicates of 'vString219_F'
			StringDistribution[] vString219_F = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString219_F[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString217_B'
			StringDistribution[] vString217_B = new StringDistribution[10];
			for(int index55 = 0; index55<10; index55++) {
				vString217_B[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__54_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__54_use_B = new DistributionStructArray<DiscreteChar,char>[10];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vChar__54_use' Backwards messages.
				vChar__54_use_B[index55] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index54 = 0; index54<8; index54++) {
					vChar__54_use_B[index55][index54] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__54__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__54__0__B = new DistributionRefArray<Dirichlet,Vector>[10];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vVector__54__0_' Backwards messages.
				vVector__54__0__B[index55] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index54 = 0; index54<8; index54++) {
					vVector__54__0__B[index55][index54] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet27.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__54__B'
			Dirichlet[][][] vVector__54__B = new Dirichlet[10][][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vVector__54_' Backwards messages.
				vVector__54__B[index55] = new Dirichlet[8][];
				for(int index54 = 0; index54<8; index54++) {
					// Create array for 'vVector__54_' Backwards messages.
					vVector__54__B[index55][index54] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__54__B[index55][index54][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet27.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__54_index55__selector_cases_0_uses_B'
			Bernoulli[][] vbool__54_index55__selector_cases_0_uses_B = new Bernoulli[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vbool__54_index55__selector_cases_0_uses' Backwards messages.
				vbool__54_index55__selector_cases_0_uses_B[index55] = new Bernoulli[27];
				vbool__54_index55__selector_cases_0_uses_B[index55][25] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][24] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][23] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][22] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][21] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][20] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][19] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][18] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][17] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][16] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][15] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][14] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][11] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][10] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][9] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][8] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][7] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][6] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][5] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][4] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][3] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][2] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][1] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][0] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][12] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][13] = Bernoulli.Uniform();
				vbool__54_index55__selector_cases_0_uses_B[index55][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__54_index55__selector_cases_0_B'
			Bernoulli[] vbool__54_index55__selector_cases_0_B = new Bernoulli[10];
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_cases_0_B[index55] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__54_index55__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__54_index55__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[10];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vbool__54_index55__selector_cases' Backwards messages.
				vbool__54_index55__selector_cases_B[index55] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__54_index55__selector_cases_B[index55][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__54_index55__selector_uses_B'
			Bernoulli[][] vbool__54_index55__selector_uses_B = new Bernoulli[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vbool__54_index55__selector_uses' Backwards messages.
				vbool__54_index55__selector_uses_B[index55] = new Bernoulli[3];
				vbool__54_index55__selector_uses_B[index55][2] = Bernoulli.Uniform();
				vbool__54_index55__selector_uses_B[index55][1] = Bernoulli.Uniform();
				vbool__54_index55__selector_uses_B[index55][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__54_index55__selector_cases_1_B'
			Bernoulli[] vbool__54_index55__selector_cases_1_B = new Bernoulli[10];
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_cases_1_B[index55] = Bernoulli.Uniform();
				// Message to 'vbool__54_index55__selector_cases_1' from StringOfLength factor
				vbool__54_index55__selector_cases_1_B[index55] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar81, 30, this.vString__27[index55]));
				// Message to 'vbool__54_index55__selector_cases' from Copy factor
				vbool__54_index55__selector_cases_B[index55][1] = ArrayHelper.SetTo<Bernoulli>(vbool__54_index55__selector_cases_B[index55][1], vbool__54_index55__selector_cases_1_B[index55]);
			}
			// Create array for replicates of 'vbool__54_index55__selector_uses_B_toDef'
			Bernoulli[] vbool__54_index55__selector_uses_B_toDef = new Bernoulli[10];
			Bernoulli vBernoulli27 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_uses_B_toDef[index55] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli27);
			}
			// Create array for replicates of 'vbool__54_index55__selector_uses_F_marginal'
			Bernoulli[] vbool__54_index55__selector_uses_F_marginal = new Bernoulli[10];
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_uses_F_marginal[index55] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli27);
			}
			// Create array for replicates of 'vbool__54_index55__selector_uses_F'
			Bernoulli[][] vbool__54_index55__selector_uses_F = new Bernoulli[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vbool__54_index55__selector_uses' Forwards messages.
				vbool__54_index55__selector_uses_F[index55] = new Bernoulli[3];
				vbool__54_index55__selector_uses_F[index55][1] = Bernoulli.Uniform();
				vbool__54_index55__selector_uses_F[index55][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__54_index55__selector_rep_B_toDef'
			Bernoulli[] vbool__54_index55__selector_rep_B_toDef = new Bernoulli[10];
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_rep_B_toDef[index55] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__54_index55__selector_uses_F[index55][1]);
			}
			// Create array for replicates of 'vbool__54_index55__selector_rep_F_marginal'
			Bernoulli[] vbool__54_index55__selector_rep_F_marginal = new Bernoulli[10];
			for(int index55 = 0; index55<10; index55++) {
				vbool__54_index55__selector_rep_F_marginal[index55] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__54_index55__selector_uses_F[index55][1]);
			}
			// Create array for replicates of 'vbool__54_index55__selector_rep_F'
			Bernoulli[][] vbool__54_index55__selector_rep_F = new Bernoulli[10][];
			for(int index55 = 0; index55<10; index55++) {
				// Create array for 'vbool__54_index55__selector_rep' Forwards messages.
				vbool__54_index55__selector_rep_F[index55] = new Bernoulli[8];
				for(int index54 = 0; index54<8; index54++) {
					vbool__54_index55__selector_rep_F[index55][index54] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__54_index55__selector_rep_B_reduced = default(Bernoulli);
			vbool__54_index55__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index54 = 0; index54<8; index54++) {
					vVector__54_rep_F_marginal[index54] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__54_rep_B_toDef[index54], this.vDirichlet27, vVector__54_rep_F_marginal[index54]);
				}
				for(int index55 = 0; index55<10; index55++) {
					for(int index54 = 0; index54<8; index54++) {
						// Message to 'vVector__54_rep' from Replicate factor
						vVector__54_rep_F[index54][index55] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__54_rep_B[index54][index55], vVector__54_rep_F_marginal[index54], index55, vVector__54_rep_F[index54][index55]);
						// Message to 'vChar__54' from Char factor
						vChar__54_F[index55][index54] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__54_rep_F[index54][index55]);
					}
					// Message to 'vString217' from StringFromArray factor
					vString217_F[index55] = StringFromArrayOp.StrAverageConditional(vChar__54_F[index55]);
					// Message to 'vString220' from Concat factor
					vString220_F[index55] = StringConcatOp.ConcatAverageConditional(this.vString218_F[index55], vString217_F[index55]);
					// Message to 'vString219_use' from Concat factor
					vString219_use_B[index55] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__27[index55]), vString220_F[index55]);
					// Message to 'vint306' from StringOfLength factor
					vint306_B[index55] = StringOfLengthOp.LengthAverageConditional(vString219_use_B[index55], vDiscreteChar81, vint306_B[index55]);
					// Message to 'vint__54_index55__0__uses' from Difference factor
					vint__54_index55__0__uses_B[index55][0] = IntegerPlusOp.BAverageConditional(22, vint306_B[index55], vint__54_index55__0__uses_B[index55][0]);
					// Message to 'vint__54_index55__0__uses' from Replicate factor
					vint__54_index55__0__uses_F[index55][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__54_index55__0__uses_B[index55], vint__54_F_reduced, 1, vint__54_index55__0__uses_F[index55][1]);
					// Message to 'vString218' from StringOfLength factor
					this.vString218_F[index55] = StringOfLengthOp.StrAverageConditional(vDiscreteChar81, vint__54_index55__0__uses_F[index55][1]);
					// Message to 'vString218_use' from Concat factor
					vString218_use_B[index55] = StringConcatOp.Str1AverageConditional(this.vString220_B[index55], vString217_F[index55]);
					// Message to 'vint__54_index55__0__uses' from StringOfLength factor
					vint__54_index55__0__uses_B[index55][1] = StringOfLengthOp.LengthAverageConditional(vString218_use_B[index55], vDiscreteChar81, vint__54_index55__0__uses_B[index55][1]);
					// Message to 'vint__54_index55__0__uses' from Replicate factor
					vint__54_index55__0__uses_F[index55][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__54_index55__0__uses_B[index55], vint__54_F_reduced, 0, vint__54_index55__0__uses_F[index55][0]);
					// Message to 'vint306' from Difference factor
					vint306_F[index55] = IntegerPlusOp.AAverageConditional(22, vint__54_index55__0__uses_F[index55][0], vint306_F[index55]);
					// Message to 'vString219' from StringOfLength factor
					vString219_F[index55] = StringOfLengthOp.StrAverageConditional(vDiscreteChar81, vint306_F[index55]);
					// Message to 'vString220' from Concat factor
					this.vString220_B[index55] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__27[index55]), vString219_F[index55]);
					// Message to 'vString217' from Concat factor
					vString217_B[index55] = StringConcatOp.Str2AverageConditional(this.vString220_B[index55], this.vString218_F[index55]);
					// Message to 'vChar__54_use' from StringFromArray factor
					vChar__54_use_B[index55] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString217_B[index55], vChar__54_F[index55], vChar__54_use_B[index55]);
					// Message to 'vbool__54_index55__selector_cases_0_uses' from Concat factor
					vbool__54_index55__selector_cases_0_uses_B[index55][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__27[index55], vString220_F[index55], vString219_F[index55]));
					// Message to 'vbool__54_index55__selector_cases_0_uses' from Difference factor
					vbool__54_index55__selector_cases_0_uses_B[index55][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(22, vint306_B[index55], vint__54_index55__0__uses_F[index55][0]));
					// Message to 'vbool__54_index55__selector_cases_0_uses' from Replicate factor
					vbool__54_index55__selector_cases_0_uses_B[index55][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__54_index55__0__uses_B[index55], vint__54_F_reduced, vint__54_index55__0__uses_F[index55]));
					// Message to 'vbool__54_index55__selector_cases_0' from Replicate factor
					vbool__54_index55__selector_cases_0_B[index55] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__54_index55__selector_cases_0_uses_B[index55], vbool__54_index55__selector_cases_0_B[index55]);
					// Message to 'vbool__54_index55__selector_cases' from Copy factor
					vbool__54_index55__selector_cases_B[index55][0] = ArrayHelper.SetTo<Bernoulli>(vbool__54_index55__selector_cases_B[index55][0], vbool__54_index55__selector_cases_0_B[index55]);
					// Message to 'vbool__54_index55__selector_uses' from Cases factor
					vbool__54_index55__selector_uses_B[index55][0] = CasesOp.BAverageConditional(vbool__54_index55__selector_cases_B[index55]);
					vbool__54_index55__selector_uses_B_toDef[index55] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__54_index55__selector_uses_B[index55], vbool__54_index55__selector_uses_B_toDef[index55]);
					vbool__54_index55__selector_uses_F_marginal[index55] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__54_index55__selector_uses_B_toDef[index55], vBernoulli27, vbool__54_index55__selector_uses_F_marginal[index55]);
					// Message to 'vbool__54_index55__selector_uses' from Replicate factor
					vbool__54_index55__selector_uses_F[index55][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__54_index55__selector_rep_B_toDef[index55], vbool__54_index55__selector_uses_F_marginal[index55], 1, vbool__54_index55__selector_uses_F[index55][1]);
					vbool__54_index55__selector_rep_F_marginal[index55] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__54_index55__selector_rep_B_toDef[index55], vbool__54_index55__selector_uses_F[index55][1], vbool__54_index55__selector_rep_F_marginal[index55]);
					for(int index54 = 0; index54<8; index54++) {
						// Message to 'vVector__54__0_' from Char factor
						vVector__54__0__B[index55][index54] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__54_use_B[index55][index54], vVector__54_rep_F[index54][index55], vVector__54__0__B[index55][index54]);
						// Message to 'vVector__54_' from Copy factor
						vVector__54__B[index55][index54][0] = ArrayHelper.SetTo<Dirichlet>(vVector__54__B[index55][index54][0], vVector__54__0__B[index55][index54]);
						// Message to 'vbool__54_index55__selector_rep' from Replicate factor
						vbool__54_index55__selector_rep_F[index55][index54] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__54_index55__selector_rep_B_reduced, vbool__54_index55__selector_rep_F_marginal[index55], index54, vbool__54_index55__selector_rep_F[index55][index54]);
						// Message to 'vVector__54_rep' from EnterPartial factor
						this.vVector__54_rep_B[index54][index55] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__54__B[index55][index54], vbool__54_index55__selector_rep_F[index55][index54], vVector__54_rep_F[index54][index55], new int[1] { 0 }, this.vVector__54_rep_B[index54][index55]);
					}
				}
				for(int index54 = 0; index54<8; index54++) {
					this.vVector__54_rep_B_toDef[index54] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__54_rep_B[index54], this.vVector__54_rep_B_toDef[index54]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index54 = 0; index54<8; index54++) {
				this.vVector__54_marginal_F[index54] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet27.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__54_marginal' from Variable factor
				this.vVector__54_marginal_F[index54] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__54_rep_B_toDef[index54], this.vDirichlet27, this.vVector__54_marginal_F[index54]);
			}
			// Create array for 'vint__54_marginal' Forwards messages.
			this.vint__54_marginal_F = new DistributionRefArray<Discrete,int>(10);
			// Create array for replicates of 'vint__54_index55__0__B'
			Discrete[] vint__54_index55__0__B = new Discrete[10];
			// Create array for replicates of 'vint__54_index55__B'
			Discrete[][] vint__54_index55__B = new Discrete[10][];
			DistributionRefArray<Discrete,int> vint__54_use_B;
			// Create array for 'vint__54_use' Backwards messages.
			vint__54_use_B = new DistributionRefArray<Discrete,int>(10);
			for(int index55 = 0; index55<10; index55++) {
				this.vint__54_marginal_F[index55] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				vint__54_use_B[index55] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vbool__54_index55__selector_uses' from Replicate factor
				vbool__54_index55__selector_uses_F[index55][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__54_index55__selector_uses_B[index55][2], vbool__54_index55__selector_uses_F_marginal[index55], 2, vbool__54_index55__selector_uses_F[index55][2]);
				// Create array for 'vint__54_index55_' Backwards messages.
				vint__54_index55__B[index55] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__54_index55__B[index55][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				}
				vint__54_index55__0__B[index55] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(23));
				// Message to 'vint__54_index55__0_' from Replicate factor
				vint__54_index55__0__B[index55] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__54_index55__0__uses_B[index55], vint__54_index55__0__B[index55]);
				// Message to 'vint__54_index55_' from Copy factor
				vint__54_index55__B[index55][0] = ArrayHelper.SetTo<Discrete>(vint__54_index55__B[index55][0], vint__54_index55__0__B[index55]);
				// Message to 'vint__54_use' from EnterPartial factor
				vint__54_use_B[index55] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__54_index55__B[index55], vbool__54_index55__selector_uses_F[index55][2], vint__54_F_reduced, new int[1] { 0 }, vint__54_use_B[index55]);
				// Message to 'vint__54_marginal' from Variable factor
				this.vint__54_marginal_F[index55] = VariableOp.MarginalAverageConditional<Discrete>(vint__54_use_B[index55], vint__54_F_reduced, this.vint__54_marginal_F[index55]);
			}
			// Create array for 'vbool__54_marginal' Forwards messages.
			this.vbool__54_marginal_F = new DistributionStructArray<Bernoulli,bool>(10);
			for(int index55 = 0; index55<10; index55++) {
				this.vbool__54_marginal_F[index55] = Bernoulli.Uniform();
				// Message to 'vbool__54_marginal' from Variable factor
				this.vbool__54_marginal_F[index55] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__54_index55__selector_uses_B_toDef[index55], vBernoulli27, this.vbool__54_marginal_F[index55]);
			}
			this.Changed_numberOfIterations_vString__27_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__27</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__27(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__27_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__27_isInitialised)) {
				return ;
			}
			for(int index54 = 0; index54<8; index54++) {
				this.vVector__54_rep_B_toDef[index54] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet27);
			}
			for(int index55 = 0; index55<10; index55++) {
				for(int index54 = 0; index54<8; index54++) {
					this.vVector__54_rep_B[index54][index55] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet27.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString218_F[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString220_B[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__27_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__27_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__27</summary>
		private void Changed_vString__27()
		{
			if (this.Changed_vString__27_isDone) {
				return ;
			}
			// Create array for 'vString__27_marginal' Forwards messages.
			this.vString__27_marginal_F = new DistributionRefArray<StringDistribution,string>(10);
			for(int index55 = 0; index55<10; index55++) {
				this.vString__27_marginal_F[index55] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__27_marginal' from DerivedVariable factor
			this.vString__27_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__27, this.vString__27_marginal_F);
			this.Changed_vString__27_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet27 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__54_rep_B_toDef'
			this.vVector__54_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__54_rep_B'
			this.vVector__54_rep_B = new Dirichlet[8][];
			for(int index54 = 0; index54<8; index54++) {
				// Create array for 'vVector__54_rep' Backwards messages.
				this.vVector__54_rep_B[index54] = new Dirichlet[10];
			}
			// Create array for replicates of 'vString218_F'
			this.vString218_F = new StringDistribution[10];
			// Create array for replicates of 'vString220_B'
			this.vString220_B = new StringDistribution[10];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__27_isDone = false;
				}
				this.Changed_numberOfIterations_vString__27_isDone = false;
			}
			this.Changed_vString__27();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__27(initialise);
			this.Changed_numberOfIterations_vString__27(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__27") {
				return this.vString__27;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__27") {
				return this.VString__27Marginal();
			}
			if (variableName=="vVector__54") {
				return this.VVector__54Marginal();
			}
			if (variableName=="vint__54") {
				return this.Vint__54Marginal();
			}
			if (variableName=="vbool__54") {
				return this.Vbool__54Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__27") {
				this.vString__27 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__54' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__54Marginal()
		{
			return this.vbool__54_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__54' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__54Marginal()
		{
			return this.vint__54_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__27' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__27Marginal()
		{
			return this.vString__27_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__54' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__54Marginal()
		{
			return this.vVector__54_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
