// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Distributions.Automata;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2504.701 at 08:49 on mercredi 17 décembre 2025.
	/// </remarks>
	public partial class Model5_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_numberOfIterations_vString__6 has executed. Set this to false to force re-execution of Changed_numberOfIterations_vString__6</summary>
		public bool Changed_numberOfIterations_vString__6_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__6 has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__6</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__6_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_Init_vString__6 has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_Init_vString__6</summary>
		public bool Changed_numberOfIterationsDecreased_Init_vString__6_isInitialised;
		/// <summary>True if Changed_vString__6 has executed. Set this to false to force re-execution of Changed_vString__6</summary>
		public bool Changed_vString__6_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'vbool__12'</summary>
		public DistributionStructArray<Bernoulli,bool> vbool__12_marginal_F;
		/// <summary>The constant 'vDirichlet6'</summary>
		public Dirichlet vDirichlet6;
		/// <summary>Message to marginal of 'vint__12'</summary>
		public DistributionRefArray<Discrete,int> vint__12_marginal_F;
		/// <summary>Field backing the vString__6 property</summary>
		private string[] vString__6_field;
		/// <summary>Message to marginal of 'vString__6'</summary>
		public DistributionRefArray<StringDistribution,string> vString__6_marginal_F;
		public StringDistribution[] vString50_F;
		public StringDistribution[] vString52_B;
		/// <summary>Message to marginal of 'vVector__12'</summary>
		public DistributionRefArray<Dirichlet,Vector> vVector__12_marginal_F;
		public Dirichlet[][] vVector__12_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet[] vVector__12_rep_B_toDef;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vString__6'</summary>
		public string[] vString__6
		{
			get {
				return this.vString__6_field;
			}
			set {
				if ((value!=null)&&(value.Length!=30)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+30)+" was expected for variable \'vString__6\'");
				}
				this.vString__6_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vString__6_isDone = false;
				this.Changed_numberOfIterationsDecreased_Init_vString__6_isInitialised = false;
				this.Changed_numberOfIterations_vString__6_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of numberOfIterations and vString__6</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_numberOfIterations_vString__6(int numberOfIterations)
		{
			if (this.Changed_numberOfIterations_vString__6_isDone) {
				return ;
			}
			// Create array for 'vVector__12_marginal' Forwards messages.
			this.vVector__12_marginal_F = new DistributionRefArray<Dirichlet,Vector>(8);
			// Create array for replicates of 'vVector__12_rep_F_marginal'
			Dirichlet[] vVector__12_rep_F_marginal = new Dirichlet[8];
			for(int index12 = 0; index12<8; index12++) {
				vVector__12_rep_F_marginal[index12] = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.vDirichlet6);
			}
			// Create array for replicates of 'vVector__12_rep_F'
			Dirichlet[][] vVector__12_rep_F = new Dirichlet[8][];
			for(int index12 = 0; index12<8; index12++) {
				// Create array for 'vVector__12_rep' Forwards messages.
				vVector__12_rep_F[index12] = new Dirichlet[30];
			}
			for(int index13 = 0; index13<30; index13++) {
				for(int index12 = 0; index12<8; index12++) {
					vVector__12_rep_F[index12][index13] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet6.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vChar__12_F'
			DistributionStructArray<DiscreteChar,char>[] vChar__12_F = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vChar__12' Forwards messages.
				vChar__12_F[index13] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index12 = 0; index12<8; index12++) {
					vChar__12_F[index13][index12] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vString49_F'
			StringDistribution[] vString49_F = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString49_F[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString52_F'
			StringDistribution[] vString52_F = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString52_F[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString51_use_B'
			StringDistribution[] vString51_use_B = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString51_use_B[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint75_B'
			Discrete[] vint75_B = new Discrete[30];
			for(int index13 = 0; index13<30; index13++) {
				vint75_B[index13] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			DiscreteChar vDiscreteChar18 = new DiscreteChar(ImmutableDiscreteChar.Create(ReadOnlyArray<ImmutableDiscreteChar.CharRange>.CreateCopy(new ImmutableDiscreteChar.CharRange[4] { new ImmutableDiscreteChar.CharRange(65, 66, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(67, 68, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(71, 72, Weight.FromLogValue(-1.3862943611198908)), new ImmutableDiscreteChar.CharRange(84, 85, Weight.FromLogValue(-1.3862943611198908)) })));
			// Create array for replicates of 'vint__12_index13__0__uses_B'
			Discrete[][] vint__12_index13__0__uses_B = new Discrete[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vint__12_index13__0__uses' Backwards messages.
				vint__12_index13__0__uses_B[index13] = new Discrete[2];
				vint__12_index13__0__uses_B[index13][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__12_index13__0__uses_B[index13][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			// Create array for replicates of 'vint__12_index13__0__uses_F'
			Discrete[][] vint__12_index13__0__uses_F = new Discrete[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vint__12_index13__0__uses' Forwards messages.
				vint__12_index13__0__uses_F[index13] = new Discrete[2];
				vint__12_index13__0__uses_F[index13][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__12_index13__0__uses_F[index13][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			Discrete vint__12_F_reduced;
			vint__12_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			// Create array for replicates of 'vString50_use_B'
			StringDistribution[] vString50_use_B = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString50_use_B[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vint75_F'
			Discrete[] vint75_F = new Discrete[30];
			for(int index13 = 0; index13<30; index13++) {
				vint75_F[index13] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
			}
			// Create array for replicates of 'vString51_F'
			StringDistribution[] vString51_F = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString51_F[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vString49_B'
			StringDistribution[] vString49_B = new StringDistribution[30];
			for(int index13 = 0; index13<30; index13++) {
				vString49_B[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Create array for replicates of 'vChar__12_use_B'
			DistributionStructArray<DiscreteChar,char>[] vChar__12_use_B = new DistributionStructArray<DiscreteChar,char>[30];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vChar__12_use' Backwards messages.
				vChar__12_use_B[index13] = new DistributionStructArray<DiscreteChar,char>(8);
				for(int index12 = 0; index12<8; index12++) {
					vChar__12_use_B[index13][index12] = DiscreteChar.Uniform();
				}
			}
			// Create array for replicates of 'vVector__12__0__B'
			DistributionRefArray<Dirichlet,Vector>[] vVector__12__0__B = new DistributionRefArray<Dirichlet,Vector>[30];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vVector__12__0_' Backwards messages.
				vVector__12__0__B[index13] = new DistributionRefArray<Dirichlet,Vector>(8);
				for(int index12 = 0; index12<8; index12++) {
					vVector__12__0__B[index13][index12] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet6.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
			}
			// Create array for replicates of 'vVector__12__B'
			Dirichlet[][][] vVector__12__B = new Dirichlet[30][][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vVector__12_' Backwards messages.
				vVector__12__B[index13] = new Dirichlet[8][];
				for(int index12 = 0; index12<8; index12++) {
					// Create array for 'vVector__12_' Backwards messages.
					vVector__12__B[index13][index12] = new Dirichlet[1];
					for(int _gateind = 0; _gateind<1; _gateind++) {
						vVector__12__B[index13][index12][_gateind] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet6.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
					}
				}
			}
			// Create array for replicates of 'vbool__12_index13__selector_cases_0_uses_B'
			Bernoulli[][] vbool__12_index13__selector_cases_0_uses_B = new Bernoulli[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vbool__12_index13__selector_cases_0_uses' Backwards messages.
				vbool__12_index13__selector_cases_0_uses_B[index13] = new Bernoulli[27];
				vbool__12_index13__selector_cases_0_uses_B[index13][25] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][24] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][23] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][22] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][21] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][20] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][19] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][18] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][17] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][16] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][15] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][14] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][11] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][10] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][9] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][8] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][7] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][6] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][5] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][4] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][3] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][2] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][1] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][0] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][12] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][13] = Bernoulli.Uniform();
				vbool__12_index13__selector_cases_0_uses_B[index13][26] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__12_index13__selector_cases_0_B'
			Bernoulli[] vbool__12_index13__selector_cases_0_B = new Bernoulli[30];
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_cases_0_B[index13] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__12_index13__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] vbool__12_index13__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[30];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vbool__12_index13__selector_cases' Backwards messages.
				vbool__12_index13__selector_cases_B[index13] = new DistributionStructArray<Bernoulli,bool>(2);
				for(int _ind0 = 0; _ind0<2; _ind0++) {
					vbool__12_index13__selector_cases_B[index13][_ind0] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'vbool__12_index13__selector_uses_B'
			Bernoulli[][] vbool__12_index13__selector_uses_B = new Bernoulli[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vbool__12_index13__selector_uses' Backwards messages.
				vbool__12_index13__selector_uses_B[index13] = new Bernoulli[3];
				vbool__12_index13__selector_uses_B[index13][2] = Bernoulli.Uniform();
				vbool__12_index13__selector_uses_B[index13][1] = Bernoulli.Uniform();
				vbool__12_index13__selector_uses_B[index13][0] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__12_index13__selector_cases_1_B'
			Bernoulli[] vbool__12_index13__selector_cases_1_B = new Bernoulli[30];
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_cases_1_B[index13] = Bernoulli.Uniform();
				// Message to 'vbool__12_index13__selector_cases_1' from StringOfLength factor
				vbool__12_index13__selector_cases_1_B[index13] = Bernoulli.FromLogOdds(StringOfLengthOp.LogEvidenceRatio(vDiscreteChar18, 50, this.vString__6[index13]));
				// Message to 'vbool__12_index13__selector_cases' from Copy factor
				vbool__12_index13__selector_cases_B[index13][1] = ArrayHelper.SetTo<Bernoulli>(vbool__12_index13__selector_cases_B[index13][1], vbool__12_index13__selector_cases_1_B[index13]);
			}
			// Create array for replicates of 'vbool__12_index13__selector_uses_B_toDef'
			Bernoulli[] vbool__12_index13__selector_uses_B_toDef = new Bernoulli[30];
			Bernoulli vBernoulli6 = Bernoulli.FromLogOdds(1.3862943611198908);
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_uses_B_toDef[index13] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vBernoulli6);
			}
			// Create array for replicates of 'vbool__12_index13__selector_uses_F_marginal'
			Bernoulli[] vbool__12_index13__selector_uses_F_marginal = new Bernoulli[30];
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_uses_F_marginal[index13] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vBernoulli6);
			}
			// Create array for replicates of 'vbool__12_index13__selector_uses_F'
			Bernoulli[][] vbool__12_index13__selector_uses_F = new Bernoulli[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vbool__12_index13__selector_uses' Forwards messages.
				vbool__12_index13__selector_uses_F[index13] = new Bernoulli[3];
				vbool__12_index13__selector_uses_F[index13][1] = Bernoulli.Uniform();
				vbool__12_index13__selector_uses_F[index13][2] = Bernoulli.Uniform();
			}
			// Create array for replicates of 'vbool__12_index13__selector_rep_B_toDef'
			Bernoulli[] vbool__12_index13__selector_rep_B_toDef = new Bernoulli[30];
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_rep_B_toDef[index13] = ReplicateOp_Divide.ToDefInit<Bernoulli>(vbool__12_index13__selector_uses_F[index13][1]);
			}
			// Create array for replicates of 'vbool__12_index13__selector_rep_F_marginal'
			Bernoulli[] vbool__12_index13__selector_rep_F_marginal = new Bernoulli[30];
			for(int index13 = 0; index13<30; index13++) {
				vbool__12_index13__selector_rep_F_marginal[index13] = ReplicateOp_Divide.MarginalInit<Bernoulli>(vbool__12_index13__selector_uses_F[index13][1]);
			}
			// Create array for replicates of 'vbool__12_index13__selector_rep_F'
			Bernoulli[][] vbool__12_index13__selector_rep_F = new Bernoulli[30][];
			for(int index13 = 0; index13<30; index13++) {
				// Create array for 'vbool__12_index13__selector_rep' Forwards messages.
				vbool__12_index13__selector_rep_F[index13] = new Bernoulli[8];
				for(int index12 = 0; index12<8; index12++) {
					vbool__12_index13__selector_rep_F[index13][index12] = Bernoulli.Uniform();
				}
			}
			Bernoulli vbool__12_index13__selector_rep_B_reduced = default(Bernoulli);
			vbool__12_index13__selector_rep_B_reduced = Bernoulli.Uniform();
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int index12 = 0; index12<8; index12++) {
					vVector__12_rep_F_marginal[index12] = ReplicateOp_Divide.Marginal<Dirichlet>(this.vVector__12_rep_B_toDef[index12], this.vDirichlet6, vVector__12_rep_F_marginal[index12]);
				}
				for(int index13 = 0; index13<30; index13++) {
					for(int index12 = 0; index12<8; index12++) {
						// Message to 'vVector__12_rep' from Replicate factor
						vVector__12_rep_F[index12][index13] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.vVector__12_rep_B[index12][index13], vVector__12_rep_F_marginal[index12], index13, vVector__12_rep_F[index12][index13]);
						// Message to 'vChar__12' from Char factor
						vChar__12_F[index13][index12] = CharFromProbabilitiesOp.CharacterAverageConditional(vVector__12_rep_F[index12][index13]);
					}
					// Message to 'vString49' from StringFromArray factor
					vString49_F[index13] = StringFromArrayOp.StrAverageConditional(vChar__12_F[index13]);
					// Message to 'vString52' from Concat factor
					vString52_F[index13] = StringConcatOp.ConcatAverageConditional(this.vString50_F[index13], vString49_F[index13]);
					// Message to 'vString51_use' from Concat factor
					vString51_use_B[index13] = StringConcatOp.Str2AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__6[index13]), vString52_F[index13]);
					// Message to 'vint75' from StringOfLength factor
					vint75_B[index13] = StringOfLengthOp.LengthAverageConditional(vString51_use_B[index13], vDiscreteChar18, vint75_B[index13]);
					// Message to 'vint__12_index13__0__uses' from Difference factor
					vint__12_index13__0__uses_B[index13][0] = IntegerPlusOp.BAverageConditional(42, vint75_B[index13], vint__12_index13__0__uses_B[index13][0]);
					// Message to 'vint__12_index13__0__uses' from Replicate factor
					vint__12_index13__0__uses_F[index13][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__12_index13__0__uses_B[index13], vint__12_F_reduced, 1, vint__12_index13__0__uses_F[index13][1]);
					// Message to 'vString50' from StringOfLength factor
					this.vString50_F[index13] = StringOfLengthOp.StrAverageConditional(vDiscreteChar18, vint__12_index13__0__uses_F[index13][1]);
					// Message to 'vString50_use' from Concat factor
					vString50_use_B[index13] = StringConcatOp.Str1AverageConditional(this.vString52_B[index13], vString49_F[index13]);
					// Message to 'vint__12_index13__0__uses' from StringOfLength factor
					vint__12_index13__0__uses_B[index13][1] = StringOfLengthOp.LengthAverageConditional(vString50_use_B[index13], vDiscreteChar18, vint__12_index13__0__uses_B[index13][1]);
					// Message to 'vint__12_index13__0__uses' from Replicate factor
					vint__12_index13__0__uses_F[index13][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(vint__12_index13__0__uses_B[index13], vint__12_F_reduced, 0, vint__12_index13__0__uses_F[index13][0]);
					// Message to 'vint75' from Difference factor
					vint75_F[index13] = IntegerPlusOp.AAverageConditional(42, vint__12_index13__0__uses_F[index13][0], vint75_F[index13]);
					// Message to 'vString51' from StringOfLength factor
					vString51_F[index13] = StringOfLengthOp.StrAverageConditional(vDiscreteChar18, vint75_F[index13]);
					// Message to 'vString52' from Concat factor
					this.vString52_B[index13] = StringConcatOp.Str1AverageConditional(SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.PointMass(this.vString__6[index13]), vString51_F[index13]);
					// Message to 'vString49' from Concat factor
					vString49_B[index13] = StringConcatOp.Str2AverageConditional(this.vString52_B[index13], this.vString50_F[index13]);
					// Message to 'vChar__12_use' from StringFromArray factor
					vChar__12_use_B[index13] = StringFromArrayOp.CharactersAverageConditional<DistributionStructArray<DiscreteChar,char>>(vString49_B[index13], vChar__12_F[index13], vChar__12_use_B[index13]);
					// Message to 'vbool__12_index13__selector_cases_0_uses' from Concat factor
					vbool__12_index13__selector_cases_0_uses_B[index13][26] = Bernoulli.FromLogOdds(StringConcatOp.LogEvidenceRatio(this.vString__6[index13], vString52_F[index13], vString51_F[index13]));
					// Message to 'vbool__12_index13__selector_cases_0_uses' from Difference factor
					vbool__12_index13__selector_cases_0_uses_B[index13][13] = Bernoulli.FromLogOdds(IntegerPlusOp.LogEvidenceRatio(42, vint75_B[index13], vint__12_index13__0__uses_F[index13][0]));
					// Message to 'vbool__12_index13__selector_cases_0_uses' from Replicate factor
					vbool__12_index13__selector_cases_0_uses_B[index13][12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(vint__12_index13__0__uses_B[index13], vint__12_F_reduced, vint__12_index13__0__uses_F[index13]));
					// Message to 'vbool__12_index13__selector_cases_0' from Replicate factor
					vbool__12_index13__selector_cases_0_B[index13] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool__12_index13__selector_cases_0_uses_B[index13], vbool__12_index13__selector_cases_0_B[index13]);
					// Message to 'vbool__12_index13__selector_cases' from Copy factor
					vbool__12_index13__selector_cases_B[index13][0] = ArrayHelper.SetTo<Bernoulli>(vbool__12_index13__selector_cases_B[index13][0], vbool__12_index13__selector_cases_0_B[index13]);
					// Message to 'vbool__12_index13__selector_uses' from Cases factor
					vbool__12_index13__selector_uses_B[index13][0] = CasesOp.BAverageConditional(vbool__12_index13__selector_cases_B[index13]);
					vbool__12_index13__selector_uses_B_toDef[index13] = ReplicateOp_Divide.ToDef<Bernoulli>(vbool__12_index13__selector_uses_B[index13], vbool__12_index13__selector_uses_B_toDef[index13]);
					vbool__12_index13__selector_uses_F_marginal[index13] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__12_index13__selector_uses_B_toDef[index13], vBernoulli6, vbool__12_index13__selector_uses_F_marginal[index13]);
					// Message to 'vbool__12_index13__selector_uses' from Replicate factor
					vbool__12_index13__selector_uses_F[index13][1] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__12_index13__selector_rep_B_toDef[index13], vbool__12_index13__selector_uses_F_marginal[index13], 1, vbool__12_index13__selector_uses_F[index13][1]);
					vbool__12_index13__selector_rep_F_marginal[index13] = ReplicateOp_Divide.Marginal<Bernoulli>(vbool__12_index13__selector_rep_B_toDef[index13], vbool__12_index13__selector_uses_F[index13][1], vbool__12_index13__selector_rep_F_marginal[index13]);
					for(int index12 = 0; index12<8; index12++) {
						// Message to 'vVector__12__0_' from Char factor
						vVector__12__0__B[index13][index12] = CharFromProbabilitiesOp.ProbabilitiesAverageConditional(vChar__12_use_B[index13][index12], vVector__12_rep_F[index12][index13], vVector__12__0__B[index13][index12]);
						// Message to 'vVector__12_' from Copy factor
						vVector__12__B[index13][index12][0] = ArrayHelper.SetTo<Dirichlet>(vVector__12__B[index13][index12][0], vVector__12__0__B[index13][index12]);
						// Message to 'vbool__12_index13__selector_rep' from Replicate factor
						vbool__12_index13__selector_rep_F[index13][index12] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__12_index13__selector_rep_B_reduced, vbool__12_index13__selector_rep_F_marginal[index13], index12, vbool__12_index13__selector_rep_F[index13][index12]);
						// Message to 'vVector__12_rep' from EnterPartial factor
						this.vVector__12_rep_B[index12][index13] = GateEnterPartialOp<Vector>.ValueAverageConditional<Dirichlet>(vVector__12__B[index13][index12], vbool__12_index13__selector_rep_F[index13][index12], vVector__12_rep_F[index12][index13], new int[1] { 0 }, this.vVector__12_rep_B[index12][index13]);
					}
				}
				for(int index12 = 0; index12<8; index12++) {
					this.vVector__12_rep_B_toDef[index12] = ReplicateOp_Divide.ToDef<Dirichlet>(this.vVector__12_rep_B[index12], this.vVector__12_rep_B_toDef[index12]);
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int index12 = 0; index12<8; index12++) {
				this.vVector__12_marginal_F[index12] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet6.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				// Message to 'vVector__12_marginal' from Variable factor
				this.vVector__12_marginal_F[index12] = VariableOp.MarginalAverageConditional<Dirichlet>(this.vVector__12_rep_B_toDef[index12], this.vDirichlet6, this.vVector__12_marginal_F[index12]);
			}
			// Create array for 'vint__12_marginal' Forwards messages.
			this.vint__12_marginal_F = new DistributionRefArray<Discrete,int>(30);
			// Create array for replicates of 'vint__12_index13__0__B'
			Discrete[] vint__12_index13__0__B = new Discrete[30];
			// Create array for replicates of 'vint__12_index13__B'
			Discrete[][] vint__12_index13__B = new Discrete[30][];
			DistributionRefArray<Discrete,int> vint__12_use_B;
			// Create array for 'vint__12_use' Backwards messages.
			vint__12_use_B = new DistributionRefArray<Discrete,int>(30);
			for(int index13 = 0; index13<30; index13++) {
				this.vint__12_marginal_F[index13] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				vint__12_use_B[index13] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				// Message to 'vbool__12_index13__selector_uses' from Replicate factor
				vbool__12_index13__selector_uses_F[index13][2] = ReplicateOp_Divide.UsesAverageConditional<Bernoulli>(vbool__12_index13__selector_uses_B[index13][2], vbool__12_index13__selector_uses_F_marginal[index13], 2, vbool__12_index13__selector_uses_F[index13][2]);
				// Create array for 'vint__12_index13_' Backwards messages.
				vint__12_index13__B[index13] = new Discrete[1];
				for(int _gateind2 = 0; _gateind2<1; _gateind2++) {
					vint__12_index13__B[index13][_gateind2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				}
				vint__12_index13__0__B[index13] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(43));
				// Message to 'vint__12_index13__0_' from Replicate factor
				vint__12_index13__0__B[index13] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(vint__12_index13__0__uses_B[index13], vint__12_index13__0__B[index13]);
				// Message to 'vint__12_index13_' from Copy factor
				vint__12_index13__B[index13][0] = ArrayHelper.SetTo<Discrete>(vint__12_index13__B[index13][0], vint__12_index13__0__B[index13]);
				// Message to 'vint__12_use' from EnterPartial factor
				vint__12_use_B[index13] = BeliefPropagationGateEnterPartialOp.ValueAverageConditional<Discrete>(vint__12_index13__B[index13], vbool__12_index13__selector_uses_F[index13][2], vint__12_F_reduced, new int[1] { 0 }, vint__12_use_B[index13]);
				// Message to 'vint__12_marginal' from Variable factor
				this.vint__12_marginal_F[index13] = VariableOp.MarginalAverageConditional<Discrete>(vint__12_use_B[index13], vint__12_F_reduced, this.vint__12_marginal_F[index13]);
			}
			// Create array for 'vbool__12_marginal' Forwards messages.
			this.vbool__12_marginal_F = new DistributionStructArray<Bernoulli,bool>(30);
			for(int index13 = 0; index13<30; index13++) {
				this.vbool__12_marginal_F[index13] = Bernoulli.Uniform();
				// Message to 'vbool__12_marginal' from Variable factor
				this.vbool__12_marginal_F[index13] = VariableOp.MarginalAverageConditional<Bernoulli>(vbool__12_index13__selector_uses_B_toDef[index13], vBernoulli6, this.vbool__12_marginal_F[index13]);
			}
			this.Changed_numberOfIterations_vString__6_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and must reset on changes to vString__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_Init_vString__6(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_Init_vString__6_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_Init_vString__6_isInitialised)) {
				return ;
			}
			for(int index12 = 0; index12<8; index12++) {
				this.vVector__12_rep_B_toDef[index12] = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.vDirichlet6);
			}
			for(int index13 = 0; index13<30; index13++) {
				for(int index12 = 0; index12<8; index12++) {
					this.vVector__12_rep_B[index12][index13] = ArrayHelper.MakeUniform<Dirichlet>(Dirichlet.Uniform(this.vDirichlet6.Dimension, Sparsity.FromSpec(StorageType.Piecewise, 0.0, 0)));
				}
				this.vString50_F[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
				this.vString52_B[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			this.Changed_numberOfIterationsDecreased_Init_vString__6_isDone = true;
			this.Changed_numberOfIterationsDecreased_Init_vString__6_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of vString__6</summary>
		private void Changed_vString__6()
		{
			if (this.Changed_vString__6_isDone) {
				return ;
			}
			// Create array for 'vString__6_marginal' Forwards messages.
			this.vString__6_marginal_F = new DistributionRefArray<StringDistribution,string>(30);
			for(int index13 = 0; index13<30; index13++) {
				this.vString__6_marginal_F[index13] = SequenceDistribution<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>,WeightFunctions<string,char,ImmutableDiscreteChar,StringManipulator,StringAutomaton>.MultiRepresentationWeightFunction<StringDictionaryWeightFunction>.Factory,StringDistribution>.Uniform();
			}
			// Message to 'vString__6_marginal' from DerivedVariable factor
			this.vString__6_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<StringDistribution,string>,string[]>(this.vString__6, this.vString__6_marginal_F);
			this.Changed_vString__6_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			this.vDirichlet6 = new Dirichlet(PiecewiseVector.FromSubvectors(65536, 9.9999999999999995E-07, new List<ConstantVector>(){ new ConstantVector(65, 65, 0.10000000000000001), new ConstantVector(67, 67, 0.10000000000000001), new ConstantVector(71, 71, 0.10000000000000001), new ConstantVector(84, 84, 0.10000000000000001) }));
			// Create array for replicates of 'vVector__12_rep_B_toDef'
			this.vVector__12_rep_B_toDef = new Dirichlet[8];
			// Create array for replicates of 'vVector__12_rep_B'
			this.vVector__12_rep_B = new Dirichlet[8][];
			for(int index12 = 0; index12<8; index12++) {
				// Create array for 'vVector__12_rep' Backwards messages.
				this.vVector__12_rep_B[index12] = new Dirichlet[30];
			}
			// Create array for replicates of 'vString50_F'
			this.vString50_F = new StringDistribution[30];
			// Create array for replicates of 'vString52_B'
			this.vString52_B = new StringDistribution[30];
			this.Constant_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_Init_vString__6_isDone = false;
				}
				this.Changed_numberOfIterations_vString__6_isDone = false;
			}
			this.Changed_vString__6();
			this.Constant();
			this.Changed_numberOfIterationsDecreased_Init_vString__6(initialise);
			this.Changed_numberOfIterations_vString__6(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vString__6") {
				return this.vString__6;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vString__6") {
				return this.VString__6Marginal();
			}
			if (variableName=="vVector__12") {
				return this.VVector__12Marginal();
			}
			if (variableName=="vint__12") {
				return this.Vint__12Marginal();
			}
			if (variableName=="vbool__12") {
				return this.Vbool__12Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vString__6") {
				this.vString__6 = (string[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__12' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__12Marginal()
		{
			return this.vbool__12_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__12' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__12Marginal()
		{
			return this.vint__12_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vString__6' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<StringDistribution,string> VString__6Marginal()
		{
			return this.vString__6_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vVector__12' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Dirichlet,Vector> VVector__12Marginal()
		{
			return this.vVector__12_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
